#!/bin/bash

# A helper program for 'keyserver-rank'.

Main()
{
    local server="$1"
    local log="$2"
    local keyid=003DB8B0CB23504F   # key id of info@endeavouros.com
    local out="$(gpg --batch --keyserver $server --search-keys info@endeavouros.com 2>/dev/null)"
    local code=$?

    if [ $code -ne 0 ] || [ -z "$(echo "$out" | grep -w "$keyid")" ] ; then
        printf "$server FAIL " >> $log
    else
        printf "$server OK " >> $log
    fi
}

Main "$@"
