#!/bin/bash

## User configurations for bash-app-translate.

# BTR_PREFER_LANG determines the target language for the translation.
# Default: empty (which means bash-app-translate takes the value from the LANG environment variable).
# Note that some translation implementations use only the 2 first letters, but some need 5 first letters depending
# on the names of the translation files (e.g. btr_${appname}_fi or btr_${appname}_pt_BR).
# Example values: "fi" or "pt_BR".
#
BTR_PREFER_LANG=""
