#!/bin/bash

# Definitions used from the environment:
#    - the 'LANG' environment variable to detect the language
#    - $0 special variable in potential warnings

# Convert any %s in a string to the corresponding parameter.
#
__BTR_printf_() {
    local fmt="$1"

    if [ "$fmt" != "${fmt/\%}" ] ; then    # fmt includes % ?
        shift
        local -r fmt_orig="$fmt"
        if [ "$1" ] ; then                 # params exist ?
            local param placeholder tmp
            local parts=()
            for param in "$@" ; do
                # Try parsing %s or %Ns where N is a number (including negative).
                readarray -t parts < <(echo "$fmt" | sed -E 's|([^%]*)(%[-]*[0-9]*s)(.*)|\1\n\2\n\3|')
                placeholder="${parts[1]}"
                case "$placeholder" in
                    "") break ;;
                    %s |  %[0-9]s |  %[0-9][0-9]s |  %[0-9][0-9][0-9]s) ;;
                    %s | %-[0-9]s | %-[0-9][0-9]s | %-[0-9][0-9][0-9]s) ;;
                    *)  echo "==> ${0##*/}: warning: could not parse '$placeholder' in '$fmt_orig'" >&2
                        break
                        ;;
                esac
                printf -v tmp "$placeholder" "$param"   # works with newlines in $param ?
                fmt="${parts[0]}${tmp}${parts[2]}"
                ((params_consumed++))
            done
        else
            echo "==> ${0##*/}: warning: positional parameter missing for '$fmt_orig'" >&2
        fi
    fi
    echo -n "$fmt"
}

# Allow for multiline strings via an array.
#
__BTR_MULTILINE_() {
    local -n _btr_array_param_="$1"
    shift
    local line
    local params=("$@")

    for line in "${_btr_array_param_[@]}" ; do
        params_consumed=0
        __BTR_printf_ "$line" "${params[@]}"
        [ $params_consumed -ne 0 ] && params=("${params[@]:$params_consumed}")
    done
}

# An app can use function BTR for translation strings.
# One or more %s in the string can be used for parameters.
#
BTR() {
    local akey="$1"
    local contents="${BTR_ARR[$akey]}"
    local params_consumed=0
    shift
    case "$contents" in
        _MULTILINE_*)  __BTR_MULTILINE_ "$contents" "$@" ;;
        *)             __BTR_printf_    "$contents" "$@" ;;
    esac
}

# Language identifier is reduced from the value of the $LANG environment variable.
# This id is used in the names of the translation files.
# Note: this implementation is not anywhere near complete...
#
__btr_get_lang_() {
    # See: /usr/share/i18n/locales
    case "$LANG" in
        nl_NL* | pt_BR* | uk_UA* | zh_CN* | zh_HK* | zh_SG* | zh_TW*)
            echo ${LANG::5} ;;
        *)
            echo ${LANG::2} ;;
    esac
}


# Some definitions that may be needed in the translations:
#
local -r BTR_exclamation='&#33;'         # '!'
local -r BTR_and='&#38;'                 # '&'
local -r BTR_question='&#63;'            # '?'
local -r BTR_exclamation_down='&#161;'   # '¡'
local -r BTR_question_down='&#191;'      # '¿'


# Grab the proper BTR_ARR contents for the app & language.
#
source "/usr/share/endeavouros/translations/btr_$1_$(__btr_get_lang_)" || exit 1
