#!/bin/bash

## Definitions used from the environment:
##    - the 'LANG' environment variable to detect the language
##    - ${BASH_SOURCE[0]} special variable in potential warnings
##
## Definitions made here which can be used in the user's app:
##    - function BTR
##
## Definitions made here which can be used in translation files:
##    - variables starting with BTR_
##
## Definitions made here which should be avoided in the user's app:
##    - function names starting with '__BTR_' and ending with '_'
##    - variables starting with '_BTR_' and ending with '_'


# Convert any %s in a string to the corresponding parameter.
#
__BTR_printf_() {
    local fmt="$1"

    if [ "$fmt" != "${fmt/\%}" ] ; then    # fmt includes % ?
        shift
        local -r fmt_orig="$fmt"
        if [ "$1" ] ; then                 # params exist ?
            local param placeholder tmp
            local parts=()
            for param in "$@" ; do
                # Try parsing %s or %Ns where N is a number (including negative).
                readarray -t parts < <(echo "$fmt" | sed -E 's|([^%]*)(%[-]*[0-9]*s)(.*)|\1\n\2\n\3|')
                placeholder="${parts[1]}"
                case "$placeholder" in
                    "") break ;;
                    %s |  %[0-9]s |  %[0-9][0-9]s |  %[0-9][0-9][0-9]s) ;;
                    %s | %-[0-9]s | %-[0-9][0-9]s | %-[0-9][0-9][0-9]s) ;;
                    *)  _BTR_important_msg_ " warning: could not parse '$placeholder' in '$fmt_orig'"
                        break
                        ;;
                esac
                printf -v tmp "$placeholder" "$param"   # works with newlines in $param ?
                fmt="${parts[0]}${tmp}${parts[2]}"
                ((params_consumed++))
            done
        else
            _BTR_important_msg_ "warning: positional parameter missing for '$fmt_orig'"
        fi
    fi
    echo -n "$fmt"
}

# Allow for multiline strings via an array.
#
__BTR_MULTILINE_() {
    local -n _btr_array_param_="$1"
    shift
    local line
    local params=("$@")

    for line in "${_btr_array_param_[@]}" ; do
        params_consumed=0
        __BTR_printf_ "$line" "${params[@]}"
        [ $params_consumed -ne 0 ] && params=("${params[@]:$params_consumed}")
    done
}

# An app can use function BTR for translation strings.
# One or more %s in the string can be used for parameters.
#
BTR() {
    local akey="$1"
    local contents="${BTR_ARR[$akey]}"
    local params_consumed=0
    shift
    case "$contents" in
        _MULTILINE_*)  __BTR_MULTILINE_ "$contents" "$@" ;;
        *)             __BTR_printf_    "$contents" "$@" ;;
    esac
}

# Language identifier is reduced from the value of the $LANG environment variable.
# This id is used in the names of the translation files.
# Note: this implementation is not anywhere near complete...
#
__BTR_get_lang_() {
    # See: /usr/share/i18n/locales
    case "$LANG" in
        nl_NL* | pt_BR* | uk_UA* | zh_CN* | zh_HK* | zh_SG* | zh_TW*)
            echo ${LANG::5} ;;
        *)
            echo ${LANG::2} ;;
    esac
}


# Some definitions that may be needed in the translations:
#
BTR_exclamation='&#33;'         # '!'
BTR_and='&#38;'                 # '&'
BTR_question='&#63;'            # '?'
BTR_exclamation_down='&#161;'   # '¡'
BTR_question_down='&#191;'      # '¿'

##############################################################################################

# _BTR_translator_ to be used in this file!
case "${BASH_SOURCE[0]}" in
    /usr/share/endeavouros/translations/*)
        _BTR_translator_="${BASH_SOURCE[0]##*/}" ;;
    *)
        _BTR_translator_=bash-app-translate ;;
esac

# For error and warning messages here.
_BTR_important_msg_() { echo "==> $_BTR_appname_: $_BTR_translator_: $1" >&2; }

[ -e "/etc/$_BTR_translator_.conf" ] && source "/etc/$_BTR_translator_.conf"

# Grab the proper BTR_ARR contents for the app & language.
#
_BTR_appname_="$1"     # optional but recommended for clarity
_BTR_lang_id_="$2"     # optional

[ "$_BTR_appname_" ] || _BTR_appname_="${0##*/}"              # name of the calling app
[ "$_BTR_lang_id_" ] || _BTR_lang_id_="${BTR_PREFER_LANG}"    # user configured target language
[ "$_BTR_lang_id_" ] || _BTR_lang_id_="$(__BTR_get_lang_)"    # automatically detected target language

_BTR_language_file_="/usr/share/endeavouros/translations/btr_${_BTR_appname_}_${_BTR_lang_id_}"

if [ -e "$_BTR_language_file_" ] ; then
    source "$_BTR_language_file_" || exit 1
else
    _BTR_important_msg_ "error: '$_BTR_language_file_' does not exist!"
    exit 1
fi
