#!/bin/bash

# Convert any %s in a string to the corresponding parameter.
#
__BTR_printf_() {
    local fmt="$1"
    local param fmt_prev
    shift
    for param in "$@" ; do
        fmt_prev="$fmt"
        fmt="${fmt/\%s/$param}"
        [ "$fmt" != "$fmt_prev" ] && ((params_consumed++))
    done
    echo -n "$fmt"
}

# Allow for multiline strings via an array.
#
__BTR_MULTILINE_() {
    local -n _btr_array_param_="$1"
    shift
    local line
    local params=("$@")

    for line in "${_btr_array_param_[@]}" ; do
        params_consumed=0
        __BTR_printf_ "$line" "${params[@]}"
        params=("${params[@]:$params_consumed}")
    done
}

# An app can use function BTR for translation strings.
# One or more %s in the string can be used for parameters.
#
BTR() {
    local akey="$1"
    local contents="${BTR_ARR[$akey]}"
    local params_consumed=0
    shift
    case "$contents" in
        _MULTILINE_*)  __BTR_MULTILINE_ "$contents" "$@" ;;
        *)             __BTR_printf_    "$contents" "$@" ;;
    esac
}

# Language identifier is reduced from the value of the $LANG environment variable.
# This id is used in the names of the translation files.
# Note: this implementation is not anywhere near complete...
#
__btr_get_lang_() {
    # See: /usr/share/i18n/locales
    case "$LANG" in
        nl_NL* | pt_BR* | uk_UA* | zh_CN* | zh_HK* | zh_SG* | zh_TW*)
            echo ${LANG::5} ;;
        *)
            echo ${LANG::2} ;;
    esac
}


# Some definitions that may be needed in the translations:
#
BTR_exclamation='&#33;'         # '!'
BTR_and='&#38;'                 # '&'
BTR_question='&#63;'            # '?'
BTR_exclamation_down='&#161;'   # '¡'
BTR_question_down='&#191;'      # '¿'


# Grab the proper BTR_ARR contents for the app & language.
#
source "/usr/share/endeavouros/translations/btr_$1_$(__btr_get_lang_)" || exit 1
