#!/bin/bash

DIE() {
    eos-color error 2
    echo -e "==> Error [$progname]:\n    $1" >&2
    eos-color reset 2
    [ "$2" ] && exit "$2" || exit 1
}

Main() {
    local -r progname=${0##*/}
    local subdir="$1"
    local dir=""
    local data
    local files=()
    local dates=()
    local sizes=()
    local ix count
    local HELLO=""
    local URLBASE=""
    local ACCOUNT=""
    local PASSWORD=""
    local APP="wget"
    local -r sep="§"

    # shellcheck disable=1091
    source "$HOME/.config/fetch-iso.conf" || return 1

    if [ -z "$HELLO" ] ; then
        if [ "$ACCOUNT$PASSWORD" ] ; then
            HELLO="$ACCOUNT:$PASSWORD"
        else
            DIE "No account/password"
        fi
    fi

    case "$subdir" in
        "") dir="$URLBASE" ;;
        *)  dir="$URLBASE/$subdir" ;;
    esac

    case "$APP" in
        curl) data=$(/bin/curl --fail -Lsm 30 -o- -u "$HELLO" "$dir")                      || DIE "Failed fetching the info page '$dir'." "$?" ;;
        wget) data=$(/bin/wget -qO - --user "${HELLO%:*}" --password "${HELLO#*:}" "$dir") || DIE "Failed fetching the info page '$dir'." "$?" ;;
    esac
    echo "$data" > /tmp/foo1
    data=$(echo "$data" | grep -P 'alt="\[   \]"|alt="\[DIR\]"|alt="\[TXT\]"')
    echo "$data" > /tmp/foo

    # directories
    echo "/ (site's root dir)"
    local dirs=() tmp=()
    readarray -t tmp < <(echo "$data" | grep 'alt="\[DIR\]"' | sed -E -e "s|.*\"indexcolname\"><a href=\"([^\"]+)\".*\"indexcollastmod\">([^<]+)<.*|\1$sep\2|g" -e 's|[ ]*$||' | grep -Pv "^\.|^archive/")
    [ "${tmp[0]}" ] && dirs+=("${tmp[@]}")
    count=${#dirs[@]}
    for ((ix=0; ix<count; ix++)) ; do
        echo "${dirs[$ix]}" # >&2           # TODO: out to stdin
    done | Sorter

    # files
    readarray -t files < <(echo "$data" | grep 'alt="\[   \]"' | sed -E -e 's|.*"indexcolname"><a href="([^"]+)".*|\1|g')
    readarray -t dates < <(echo "$data" | grep 'alt="\[   \]"' | sed -E -e 's|.*"indexcollastmod">[ ]*([^<]+)<.*|\1|g' -e 's|[ ]*$||')
    readarray -t sizes < <(echo "$data" | grep 'alt="\[   \]"' | sed -E -e 's|.*"indexcolsize">[ ]*([^<]+)<.*|\1|g'    -e 's|[ ]*$||')
    count=${#files[@]}
    for ((ix=0; ix<count; ix++)) ; do
        echo "${files[$ix]}$sep${dates[$ix]}$sep${sizes[$ix]}"
    done | Sorter
}

Sorter() { column -t -s"$sep" | sort -k2 -k3 ; }

Main "$@"
