#!/bin/bash

# Avoid unnecessary reboots: don't notify if an updated package is
# - not currently running (e.g. alternative kernel)
# - not in use (e.g. alternative driver)

IsRunningKernel() {
    if [ -z "$running_kernel" ] ; then
        running_kernel=$(cat /proc/cmdline | awk '{print $1}' | sed 's|^.*/vmlinuz-\(.*\)$|\1|')
    fi
    test "$1" =  "$running_kernel"
}

DoNotify() { /usr/bin/eos-reboot-required ; exit 0 ; }

Main() {
    local targets=$(cat)  # list of updated package names from the hook (stdin)
    local target
    local running_kernel=""

    for target in $targets ; do
        case "$target" in
            linux | linux-lts | linux-zen | linux-hardened | linux-lts?? | linux-lts???)
                # Note: only official and older LTS kernels are checked.
                IsRunningKernel "$target" && DoNotify
                ;;
            nvidia)
                IsRunningKernel linux && DoNotify
                ;;
            nvidia-lts)
                IsRunningKernel linux-lts && DoNotify
                ;;
            btrfs-progs)
                # Notify only if btrfs is in use
                if [ -n "$(/usr/bin/df -hT | awk '{print $2}' | grep -w btrfs)" ] ; then
                    DoNotify
                fi
                ;;
            *)
                DoNotify
                ;;
        esac
    done
}

Main "$@"
