#!/bin/bash

# Run eos hooks related commands.

Lsb_release() {
    local file=/etc/lsb-release

    if [ -z "$(grep "^DISTRIB_CODENAME=" $file)" ] ; then
        # add missing DISTRIB_CODENAME=
        echo "DISTRIB_CODENAME=rolling" >> $file
    fi
    sed -i $file \
        -e 's|^DISTRIB_ID=.*$|DISTRIB_ID=EndeavourOS|' \
        -e 's|^DISTRIB_CODENAME=.*$|DISTRIB_CODENAME=rolling|' \
        -e 's|^DISTRIB_DESCRIPTION=.*$|DISTRIB_DESCRIPTION=\"EndeavourOS Linux\"|'
}

Os_release() {
    local file=/usr/lib/os-release
    local eosfile=/usr/lib/endeavouros-release

    # Get URLs from the EndeavourOS web site!
    local home=https://endeavouros.com
    local data=$(curl -Lsm 10 -o- $home)
    local doc=$(echo "$data" | grep ">Wiki<" | sed 's|.*\(https://[^"]*\).*|\1|')
    local support=https://forum.endeavouros.com
    local bugs=https://forum.endeavouros.com/c/arch-based-related-questions/bug-reports

    # bugs=https://github.com/endeavouros-team

    [ -n "$doc" ] || doc=https://discovery.endeavouros.com

    sed -i $file \
        -e 's|^NAME=.*$|NAME=EndeavourOS|' \
        -e 's|^PRETTY_NAME=.*$|PRETTY_NAME=EndeavourOS|' \
        -e "s|^HOME_URL=.*$|HOME_URL='$home'|" \
        -e "s|^DOCUMENTATION_URL=.*$|DOCUMENTATION_URL='$doc'|" \
        -e "s|^SUPPORT_URL=.*$|SUPPORT_URL='$support'|" \
        -e "s|^BUG_REPORT_URL=.*$|BUG_REPORT_URL='$bugs'|" \
        -e "s|^LOGO=.*$|LOGO=endeavouros|" \
        -e "s|^ID=.*$|ID=endeavouros|" \
        -e "s|^ID_LIKE=.*$|ID_LIKE=arch|"

    if [ -z "$(grep "^ID_LIKE=" $file)" ] && [ -n "$(grep "^ID=" $file)" ] ; then
        # add missing ID_LIKE=
        sed -i $file -e '/^ID=/a \ID_LIKE=arch'
    fi
    if [ -r $eosfile ] ; then
        # fix BUILD_ID for EndeavourOS
        local buildid="$(grep "^VERSION=" $eosfile | awk '{print $1}' | cut -d '=' -f 2)"
        sed -i $file -e "s|^BUILD_ID=.*$|BUILD_ID=$buildid|"
    fi
}

Issues() {
    sed -i 's|Arch|EndeavourOS|g' /etc/issue /usr/share/factory/etc/issue
}

Main()
{
    local hookname="$1"

    case "$hookname" in
        os-release)  Os_release ;;
        lsb-release) Lsb_release ;;
        "")          Os_release
                     Lsb_release
                     Issues
                     ;;
    esac
}

Main "$@"
