#!/bin/bash

# To be called from eos-reboot-required.hook.

# Implementation using libnotify.

_other_reboot_required() {
    local msg="Reboot is recommended due to the upgrade of core system package(s)."
    local title="Reboot recommended!"

    # at TTY
    echo "==> INFO: $msg" >&2

    # notification
    local xx
    for xx in "$DESKTOP_SESSION" "$XDG_CURRENT_DESKTOP" ; do
        if [ -n "$xx" ] ; then
            break
        fi
    done
    if [ -n "$xx" ] ; then
        local user userid cmd

        for user in $(/usr/bin/users) ; do
            userid=$(/usr/bin/id -u $user)
            cmd=(DISPLAY=:0 DBUS_SESSION_ADDRESS=unix:path=/run/user/$userid/bus /usr/bin/notify-send)
            cmd+=(--icon=system-reboot --urgency=critical)
            cmd+=("\"$title\"")
            cmd+=("\"$msg\"")
            /usr/bin/su $user -c "${cmd[*]}"
        done
    fi
}
_other_reboot_required
unset -f _other_reboot_required
