#!/bin/bash

PROBLEM() {
    local msg="$1"
    local problem=(
        eos_yad --form --image=$WELCOME_ICON_ERROR
        --title="ARM installer problem"
        --text="$msg"
        --button=yad-quit:1
    )
    "${problem[@]}"
}

ARM_installer_in_terminal() {
    local urls=(
        https://github.com/endeavouros-arm/images.git
        # https://github.com/pudges-place/exper-images.git
    )
    local url ix count=${#urls[@]}
    local errcode
    local msg
    local targetdir=/tmp/arm-install

    rm -rf $targetdir

    for ((ix=0; ix < $count; ix++)) ; do
        url="${urls[$ix]}"
        git clone $url $targetdir 2>/dev/null
        errcode=$?
        if [ $errcode -eq 0 ] ; then
            if [ "$Manuels_internal_testing" = "yes" ] ; then
                PROBLEM "$FUNCNAME called for testing only."
                return
            fi
            cd $targetdir
            chmod +x image-install-calamares.sh                                 # sudo not needed here?
            xfce4-terminal --maximize -e "sudo ./image-install-calamares.sh"
            return
        else
            msg="ARM installer fetch failed (git code $errcode) from\n<tt>$url</tt>\n\n"
            if [ $ix -lt $((count - 1)) ] ; then
                PROBLEM "${msg}Next URL to try:\n<tt>${urls[$((ix+1))]}</tt>\n"
            else
                PROBLEM "${msg}Bailing out.\n"
                return
            fi
        fi
    done
}
export -f ARM_installer_in_terminal

InfoPage() {
    local browser="firefox"
    [ -x /usr/bin/$browser ] || browser="xdg-open"
    $browser https://arm.endeavouros.com/installation
}
export -f InfoPage

Main() {
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

    local info_url="https://arm.endeavouros.com/installation"
    local icon=$WELCOME_ICON_INSTALL_OFFICIAL
    local title="EndeavourOS ARM image installer"
    local text=""
    text+="Starting to install the EndeavourOS ARM image\n"
    text+="to your external storage device.\n"
    text+="Please follow the instructions in the terminal window.\n"
    text+="\n"
    text+="Before starting the ARM Installer, ensure you have a storage device\n"
    text+="plugged into a USB port to receive the image.\n"
    text+="Note that the download size of the image is about 1.5 GB.\n"
    text+="Click <b>More Info</b> for further details.\n"

    local cmd=(
        eos_yad
        --form --align-buttons --use-interp --image=$icon
        --title="$title"
        --text="$text"
        --button="Start ARM Installer!$icon!Install EndeavourOS ARM image":5
        --button='More Info!user-info!More details on the wiki page':"InfoPage"
        --button=yad-cancel:1
    )
    "${cmd[@]}"
    case "$?" in
        5) ARM_installer_in_terminal ;;
    esac
    return 0
}

Main "$@"
