#!/bin/bash

PROBLEM() {
    local msg="$1"
    local problem=(
        eos_yad --form --image=$WELCOME_ICON_ERROR
        --title="ARM installer problem"
        --text="$msg"
        --button=yad-quit:1
    )
    "${problem[@]}"
}

ARM_installer_in_terminal() {
    if [ "$Manuels_internal_testing" = "yes" ] ; then
        PROBLEM "$FUNCNAME called for testing only."
        return
    fi
    local errcode
    git clone https://github.com/pudges-place/exper-images.git /tmp/arm-install 2>/dev/null
    errcode=$?
    if [ $errcode -ne 0 ] ; then
        PROBLEM "Fetching the ARM installer failed (git error code $errcode)."
        return
    fi
    cd /tmp/arm-install
    chmod +x image-install-calamares.sh                                 # sudo not needed here?
    xfce4-terminal --maximize -e "sudo ./image-install-calamares.sh"

}
export -f ARM_installer_in_terminal

InfoPage() {
    local browser="firefox"
    [ -x /usr/bin/$browser ] || browser="xdg-open"
    $browser https://arm.endeavouros.com/installation
}
export -f InfoPage

Main() {
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1

    local info_url="https://arm.endeavouros.com/installation"
    local icon=calamares
    local title="EndeavourOS ARM image installer"
    local text=""
    text+="Starting to install the EndeavourOS ARM image\n"
    text+="to your external storage device.\n"
    text+="Please follow the instructions in the terminal window.\n"
    text+="\n"
    text+="Before starting the ARM Installer, ensure you have a storage device\n"
    text+="plugged into a USB port to receive the image.\n"
    text+="Note that the download size of the image is about 1.5 GB.\n"
    text+="Click <b>More Info</b> for further details.\n"

    local cmd=(
        eos_yad
        --form --align-buttons --use-interp --image=$icon
        --title="$title"
        --text="$text"
        --button="Start ARM Installer!$icon!Install EndeavourOS ARM image":5
        --button='More Info!user-info!More details on the wiki page':"InfoPage"
        --button=yad-cancel:1
    )
    "${cmd[@]}"
    case "$?" in
        5) ARM_installer_in_terminal ;;
    esac
    return 0
}

Main "$@"
