#!/bin/bash
#
# Update (=install latest) calamares, either current or test.
#
# Make sure /etc/pacman.conf contains proper repo definition,
# and the databases are updated.
#

MakeSureRepoIsOk() {
    local file=/etc/pacman.conf
    local repo=endeavouros_calamares
    local linerepo="[$repo]"
    local lineserver='Server = https://github.com/endeavouros-team/mirrors/releases/download/$repo'

    if [ -z "$(grep "^\[$repo\]$" $file)" ] ; then
        cmds+=" ; printf '\n%s\n%s\n' '$linerepo' '$lineserver' >> $file"
    fi
}

AskType() {
    while true ; do
        read -p "Give type of calamares (current, test): " >&2
        case "$REPLY" in
            test|current) type="$REPLY" ; break ;;
            [qQ]*) exit 0 ;;
        esac
        echo "'$REPLY' is not supported." >&2
    done
}

Usage() {
    cat <<EOF >&2
Usage: $0 [options] [type]

options:
    -h | --help          This help.

type:
    current       Use the 'current' version of calamares. (default)
    test          Use the 'test' version of calamares.
    ask           Ask user about the version of calamares [current,test].
EOF
}

Main()
{
    local type="$1"
    local cmds=":"

    case "$type" in
        test) ;;
        current) ;;
        ask) AskType ;;
        -h | --help) Usage ; return ;;
        *) type=current ;;
    esac

    MakeSureRepoIsOk

    cmds+=" ; pacman -Syy calamares_$type"

    echo "Executing commands: $cmds" >&2
    echo "Elevated privileges required."
    pkexec bash -c "$cmds"
}

Main "$@"
