#!/bin/bash

# New script for using calamares.
#
# Note that this script can be called directly from the terminal,
# or it can be called from the Welcome app.

GUIDIE() {
    # show error in the terminal and log
    echo "$progname: $1" | sed -e 's|<tt>||g' -e 's|</tt>||g'  # remove some formatting tags

    # show the error in a yad window
    local cmd=(
        eos_yad --form --title="Error detected"
        --text="<tt>$progname</tt>:\n$1\n"
        --button=yad-quit:1
    )
    "${cmd[@]}"

    exit 1
}

### Provides the install log contents. ###
FollowFile() {
    local tailfile="$1"
    local term_title="$2"
    local xpos="$3"
    local ypos="$4"

    xfce4-terminal -T "$term_title" --geometry=120x20+$xpos+$ypos -x tail -f "$tailfile" &
}

### Provides the pacman log. ###
CatchChrootedPacmanLog() {
    local pacmanlog=""
    local lockfile="$HOME/.$progname.lck"

    # wait until pacman.log is available in the chrooted system, then follow the log in background
    while true ; do
        sleep 2
        pacmanlog="$(/usr/bin/ls -1 /tmp/calamares-root-*/var/log/pacman.log 2>/dev/null | /usr/bin/tail -n 1)"
        if [ -n "$pacmanlog" ] ; then
            # pacman.log detected!
            [ -r "$lockfile" ] && return
            /usr/bin/touch "$lockfile"
            FollowFile "$pacmanlog" "Pacman log" 400 50
            break
        fi
    done
}

### Starts logging into the install log. ###
InstallLog_Start() {
    cat <<EOF > $log
########## $log by $progname
########## Started (UTC): $(date -u "+%x %X")
########## Install mode: $mode
########## ISO version: $(cat /usr/lib/endeavouros-release | cut -d'=' -f2)

EOF
    FollowFile "$log" "Install log" 20 20
}

### Starts calamares and runs it in the background. ###
Calamares_Start() {
    pkexec calamares -style kvantum -c /etc/calamares/ -d >> $log &
}

### Dialog that asks for the online or offline edition. ###
AskMode() {
    local inet_no="Internet connection is not required"
    local inet_yes="Internet connection is required"
    local ret=0
    local official_online="Online"
    local official_offline="Offline"
    local txt

    txt=""
    txt+="$(ltr cal_info3)"
    txt+="$(ltr cal_info2)"

    local cmd=(
        eos_yad --form --title="$(ltr cal_choose)"
        --image=system-os-installer
        --text="$txt"
        --buttons-layout=spread
        --button="Online!!Vanilla theming, internet required":12
        --button="Offline!!Xfce, EndeavourOS theming, internet not required":14
    )
    cmd+=(
        --field=' Install Log on Terminal!Show overall log about install on a terminal':CHK $ShowInstallLog
        --field=' Pacman Log on Terminal!Show package management log on a terminal':CHK      $ShowPacmanLog
        --field='':LBL ""
    )

    local result
    result="$("${cmd[@]}")"       # ask mode from the user

    ret=$?

    # set the install mode, or exit on error
    case "$ret" in
        11|12) mode=online ;;
        13|14) mode=offline ;;
        252|*) exit $ret ;;
    esac
    ShowInstallLog=$(echo "$result" | cut -d'|' -f1)
    ShowPacmanLog=$( echo "$result" | cut -d'|' -f2)
}

### Starts the calamares installer process and logging. ###
InstallWithLogs() {
    if [ "$ShowInstallLog" = "TRUE" ] ; then
        InstallLog_Start
    fi
    Calamares_Start

    if [ "$ShowPacmanLog" = "FALSE" ] ; then
        sleep 5
        return
    fi

    case "$mode" in
        online | community)
            CatchChrootedPacmanLog
            ;;
        offline)
            # no pacman log for offline install
            CatchChrootedPacmanLog
            ;;
    esac
}

run_hotfix_start() {
    local file=hotfix-start.bash
    local url=$(eos-github2gitlab https://raw.githubusercontent.com/endeavouros-team/ISO-hotfixes/main/$file)

    if wget --timeout=30 -q -O $file $url ; then
        all_sudo_commands+="; bash $PWD/$file"
        all_sudo_commands+="; echo '===> Hotfixes definition file $file executed.'"
    else
        all_sudo_commands+="; echo '===> Fetching the hotfixes definition file failed!'"
    fi
}

###  Everything starts in the Main function. ###
Main() {
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || exit 1
    source /usr/share/endeavouros/scripts/translations.bash || exit 1
    export -f eos_yad

    local lang="$1"
    local mode="$2"                             # 'community' or '' (empty)
    local ShowInstallLog="$3"
    local ShowPacmanLog="$4"
    local progname="$(basename "$0")"           # for help and messages
    local Home=/home/liveuser                   # liveuser's home folder
    local log=$Home/endeavour-install.log       # install log
    local cfolder=/etc/calamares                # folder for calamares configuration files
    local all_sudo_commands=":"                 # all root commands will be collected to this variable!
    local workdir=""

    # change efiBootloaderId in bootloader.conf:
    sed -i $cfolder/modules/bootloader.conf \
        -e "s|^efiBootloaderId:.*|efiBootloaderId: \"endeavouros-$(shuf -i 1000-9999 -n1)\"|"

    if [ "$I_am_only_testing" = "true" ] ; then
        Home=$HOME
        #EOS_FILESERVER_SITE=github
        mode=community
        lang=en
        ShowInstallLog=FALSE
        ShowPacmanLog=FALSE
    fi

    workdir=$(mktemp -d $Home/work.XXXXX) || GUIDIE "creating work folder failed."

    _init_translations $lang || { GUIDIE "language init failed" ; }

    # asks the value for $mode
    case "$mode" in
        "" | test) AskMode ;;
    esac
    case "$mode" in
        online) ShowPacmanLog=FALSE ;;  # calamares 3.2.46 shows package install progress bar
    esac

    if eos-connection-checker ; then
        run_hotfix_start              # run possible hotfixes before copying settings.conf file
    fi

    # copy config files based on $mode

    pushd $workdir 2>/dev/null || GUIDIE "cannot go to folder $workdir"

    case "$mode" in
        online | offline | community)
            all_sudo_commands+="; cp $cfolder/settings_$mode.conf $cfolder/settings.conf"
            all_sudo_commands+="; echo '===> File settings.conf updated.'"
            ;;
        *)
            GUIDIE "unsupported mode '$mode'"
            ;;
    esac

    # now actually run hotfixes and copy settings.conf
    sudo bash -c "${all_sudo_commands[*]}"

    popd 2>/dev/null
    rm -rf $workdir

    if [ "$I_am_only_testing" = "true" ] ; then
        return
    fi

    # finally: run calamares with logs (install, pacman)
    InstallWithLogs
}

Main "$@"
