#!/bin/bash

#################################################################################
EOS_SCRIPTS_YAD=/usr/share/endeavouros/scripts/eos-script-lib-yad
source $EOS_SCRIPTS_YAD || {
    echo "ERROR: cannot find $EOS_SCRIPTS_YAD" >&2
    exit 1
}
unset EOS_SCRIPTS_YAD

export -f eos_yad
export -f eos_yad__detectDE
export -f eos_yad_GetDesktopName
#################################################################################

DIE() {
    echo "$1" >&2
    echo "$1" | \
        eos_yad --text-info --title="Error" --image=error --button=yad-ok:0 \
                --width=500 --height=300
    exit 1
}

Usage() { echo "Usage: $progname" ; }

Main()
{
    local progname="$(basename "$0")"
    local DE="$(eos_yad_GetDesktopName)"
    local picprefix=/usr/share/endeavouros/backgrounds/
    local msg
    local arg
    local pic=""
    local setter=eos-wallpaper-set

    setter=$HOME/EOS/PKGBUILDS/eos-bash-shared/eos-wallpaper-set   # TESTING !!!

    [ -n "$1" ] && DIE "$(Usage)"

    case "$DE" in
        BUDGIE)         $setter endeavouros_budgie.png ;;
        CINNAMON)       $setter endeavouros_cinnamon.png ;;
        DEEPIN)         $setter endeavouros_deepin.png ;;
        GNOME | GNOME3) $setter endeavouros_gnome.png ;;
        KDE)            $setter endeavouros_plasma.png ;;
        LXQT)           $setter endeavouros_lxqt.png ;;
        MATE)           $setter endeavouros_mate.png ;;
        XFCE)           $setter endeavouros_xfce4.png ;;
        I3)             $setter endeavouros_i3.png ;;
        *) DIE "Sorry, desktop '$DE' is not supported." ;;
    esac
}

Main "$@"
