#!/bin/bash

# Kill yad processes that have no options ("--notebook" or "--plug" etc.).

Main()
{
    sleep 0.1

    local bad="$(/usr/bin/pgrep -u "$LOGNAME" -a yad | /usr/bin/grep -P "^[0-9]* /usr/bin/yad[ ]*$|^[0-9]* yad[ ]*$")"
    if [ -n "$bad" ] ; then
        printf "Killing yad zombies:\n%s\n" "$bad"
        kill $(echo "$bad" | awk '{print $1}')
        printf "%s: killed yad zombies:\n%s\n" "$(date '+%x %X%p')" "$bad"
    else
        echo "No yad zombies."
    fi
}

Main "$@"
