#!/bin/bash

# Usage: eos-set-background-picture [filename]
# where
#    filename      Picture file name (optional).

#################################################################################
EOS_SCRIPTS_YAD=/usr/share/endeavouros/scripts/eos-script-lib-yad
test -r  $EOS_SCRIPTS_YAD || {
    echo "ERROR: cannot find $EOS_SCRIPTS_YAD" >&2
    exit 1
}
source $EOS_SCRIPTS_YAD
unset EOS_SCRIPTS_YAD

#export -f eos_yad
export -f eos_yad_terminal
export -f eos_yad_check_internet_connection
export -f eos_yad_GetArgVal
export -f eos_yad_RunCmdTermBash
export -f eos_yad_problem
export -f eos_yad_DIE
export -f eos_yad_WARN
export -f eos_yad__detectDE
export -f eos_yad_GetDesktopName
#################################################################################

eos_yad() { GDK_BACKEND=x11 /usr/bin/yad "$@" ; }

eos_yad_infomsg() {
    local msg="$1"
    echo "$msg" >&2
    eos_yad --form --text="$msg" --title="Message" --tail --wrap --image=info \
            --button=yad-quit:0 "$@"
}

DIE() {
    echo "$1" >&2
    echo "$1" | \
        eos_yad --text-info --title="Error" --image=error --button=yad-ok:0 \
                --width=500 --height=300
    exit 1
}

XfceSetWallpaper() {
    # Set all "last-image" values in file $conf to picture $pic

    local impl=2  # 2 = best

    case "$impl" in
        0)
            local conf="$HOME/.config/xfce4/xfconf/xfce-perchannel-xml/xfce4-desktop.xml"
            test -r "$conf" || DIE "Config file '$conf' does not exist."
            sed -i "$conf" -e 's|name="last-image".*$|name="last-image" type="string" value="'"$pic"'"/>|'
            eos_yad_infomsg "Reboot is required for the changes to take effect."
            ;;
        1)
            local prop
            for prop in $(xfconf-query --channel xfce4-desktop --list | grep /last-image$) ; do
                xfconf-query --channel xfce4-desktop --property $prop --set "$pic"
            done
            eos_yad_infomsg "Reboot is required for the changes to take effect."
            ;;
        2)
            local monitors=($(xrandr | grep -w connected | awk '{print $1}'))
            local monitor mon prop

            for monitor in "${monitors[@]}" ; do
                mon=monitor${monitor}
                prop=$(xfconf-query --channel xfce4-desktop --list | grep  /last-image$  | grep $mon)
                xfconf-query --channel xfce4-desktop --property $prop --set "$pic"
            done
            ;;
    esac
}

AssertPicture() {
    local fallback_picture="$1"
    local use_file_prefix="$2"

    test -n "$pic" || pic="$fallback_picture"

    case "$pic" in
        file://*) pic="${pic:7}" ;;
        /*) ;;
        *) test -r "$pic" && pic="$PWD/$pic" ;;
    esac
    test -r "$pic" || DIE "Picture file '$pic' does not exist."

    if [ "$use_file_prefix" = "no" ] ; then
        case "$pic" in
            file://*) pic="${pic:7}" ;;
        esac
    else
        case "$pic" in
            file://*) ;;
            *) pic="file://$pic" ;;
        esac
    fi
    if [ "$force_change" = "no" ] ; then
        eos_yad --form --text="Want to change wallpaper to '$pic'?" \
                --title="Changing wallpaper" --image=stock_dialog-question \
                --button=yad-no:1 --button=yad-yes:0 --geometry=+80+80
    fi
}

Usage() {
    echo "Usage: $(basename "$0") [-f | --force] wallpaper-file"
    echo "where"
    echo "   -f | --force       Do not ask for confirmation."
    echo "   wallpaper-file     Wallpaper file name (with full path)."
}

Main()
{
    local DE="$(eos_yad_GetDesktopName)"
    local picprefix=/usr/share/endeavouros/backgrounds/endeavouros_
    local picprefix_std=$picprefix
    local force_change=no
    local arg
    local pic=""

    for arg in "$@" ; do
        case "$arg" in
            -f | --force)
                force_change=yes
                ;;
            -*)
                local msg="$(printf "\n%s\n\n" "Unsupported option '$arg'." ; Usage)"
                DIE "$msg"
                ;;
            *)
                pic="$arg"    # filename with absolute path and with or without leading "file://"
                ;;
        esac
    done

    if [ ! -r ${picprefix}xfce4.png ] ; then
        picprefix=/usr/share/backgrounds/endeavouros/endeavouros_
        echo "Warning: EndeavourOS wallpapers not found at '$picprefix_std'!" >&2
        echo "Trying '$picprefix' ..." >&2
    fi
    if [ ! -r ${picprefix}xfce4.png ] ; then
        DIE "EndeavourOS wallpapers not found at '$picprefix_std'!"
    fi

    echo "Setting desktop wallpaper for '$DE' ..." >&2

    case "$DE" in
        BUDGIE)
            AssertPicture ${picprefix}budgie.png && \
                gsettings set org.gnome.desktop.background picture-uri "$pic"
            ;;
        CINNAMON)
            AssertPicture ${picprefix}cinnamon.png && \
                gsettings set org.cinnamon.desktop.background picture-uri "$pic"
            ;;
        DEEPIN)
            AssertPicture ${picprefix}deepin.png && \
                dconf write /com/deepin/wrap/gnome/desktop/background/picture-uri "'$pic'"  # Note: extra quotes required!
            ;;
        GNOME | GNOME3)
            AssertPicture ${picprefix}gnome.png && \
                gsettings set org.gnome.desktop.background picture-uri "$pic"
            ;;
        KDE)
            AssertPicture ${picprefix}plasma.png no && \
                python3 /usr/share/endeavouros/scripts/ksetwallpaper.py "$pic"
            # see also:
            # https://www.kubuntuforums.net/showthread.php/66762-Right-click-wallpaper-changer?p=387392&viewfull=1#post387392
            ;;
        LXQT)
            AssertPicture ${picprefix}lxqt.png no && \
                pcmanfm-qt --set-wallpaper="$pic"
            ;;
        MATE)
            AssertPicture ${picprefix}mate.png no && \
                gsettings set org.mate.background picture-filename "$pic"
            ;;
        XFCE)
            AssertPicture ${picprefix}xfce4.png no && \
                XfceSetWallpaper
            ;;
        *)
            DIE "Sorry, desktop '$DE' is not supported."
            ;;
    esac
}

Main "$@"
