#!/bin/bash

IsDEInstalled() {
    case "$1" in
        plasma) pacman -Q plasma-framework >& /dev/null ;;
        deepin) pacman -Q deepin-session-ui >& /dev/null ;;
        gnome)  pacman -Q gnome-session >& /dev/null ;;
        lxde)   pacman -Q lxde-common >& /dev/null ;;
        lxqt)   pacman -Q lxqt-session >& /dev/null ;;
        mate)   pacman -Q mate-session-manager >& /dev/null ;;
        xfce)   pacman -Q xfce4-session >& /dev/null ;;
        *)      pacman -Q $1 &>/dev/null ;;
    esac
}

SelectDesktop() {
    local xx
    local cmd=(yad --list --radiolist --title="Install another Desktop Environment" --width=400 --height=300)
    cmd+=(--column="Select":rd --column="DE name")
    for xx in plasma deepin enlightenment gnome lxde lxqt mate xfce i3 ; do
        IsDEInstalled "$xx" || cmd+=(false "$xx") # won't show the de
    done
    echo "$( "${cmd[@]}" | cut -d '|' -f 2)"
}

yad_infomsg() {
    yad --text-info --title="Info" --width=400 --wrap  --height=300 --button=yad-ok:0 "$@"
}

main()
{
    local pkgs
    local de="$(SelectDesktop)"

    manual_select(){
        local _cmd="yad --list --checklist --title=\"Select one or more packages\" --width=400 --height=300 --column=\"Check\" --column=\"Package name\""
        local _temp
        yad --yesno --title="$1" --width=200 --height=100 --text="Do you want to manually select extra packages? Click cancel to install them all (recomended)"
        if (( ! $? )); then
            local _pkgs=("$(pacman -Sg $1 | cut -d' ' -f2)")
            for _temp in ${_pkgs[@]}; do
                pacman -Q $_temp &>/dev/null || _cmd+=" true $_temp"
            done
            local _pkg="$(eval $_cmd | awk -F"|" '{print $2}')"
        fi
    }

    case "$de" in
#       budgie)        pkgs=(budgie-desktop gnome) ;;
        cinnamon)      pkgs="cinnamon system-config-printer gnome-keyring blueberry cinnamon-translations" ;;
        deepin)        pkgs="deepin networkmanager"
                       pkgs+=" $(manual_select deepin-extra)" ;;
        enlightenment) pkgs="enlightenment terminology" ;;
        gnome)         pkgs="gnome"
                       pkgs+=" $(manual_select gnome-extra)" ;;
        lxde)          pkgs="lxde" ;;
        lxqt)          pkgs="lxqt sddm oxygen-icons" ;;
        mate)          pkgs="mate system-config-printer blueman"
                       pkgs+=" $(manual_select mate-extra)" ;;
        plasma)        pkgs="plasma-meta"
                       pkgs+=" $(manual_select kde-applications)" ;;
        xfce)          pkgs="xfce4"
                       pkgs+=" $(manual_select xfce4-goodies)" ;;
        i3)            tmpfile=$(mktemp) 
cat <<EOF > $tmpfile
echo "please wait while we set up i3 for you"
git clone https://github.com/killajoe/i3-EndeavourOS.git /tmp/i3 1>/dev/null
cd /tmp/i3
cp -R .config/i3 ~/.config/
chmod -R +x ~/.config/i3/scripts
cp .Xresources ~/
su -c "sudo pacman -S --needed --noconfirm - < packages-repository.txt"
EOF
                       eos_yad_RunCmdTermBash "chmod +x \"$tmpfile\"; \"$tmpfile\""
                       exit $?
                       rm -f "$tmpfile" ;;
        *) return ;;
    esac

    # extra stuff, leaving them for now. @Debdut Chakraborty
    case "$de" in
        cinnamon)
            xx="xf86-video-intel"
            pacman -Q "$xx" >& /dev/null && {
                echo "Recommended to uninstall package '$xx' for DE '$de'." | yad_infomsg
            }
            ;;
        # plasma)
        #     test "$(WaylandSupport)" = "yes" && pkgs+=(plasma-wayland-session)
        #     ;;
    esac

    eos_yad_RunCmdTermBash "su -c \"pacman -S --needed $pkgs --noconfirm\""
}

main