#!/bin/bash
#
# Helper for the 'su -c' command
# (understands spaces in command parameters).

Usage() {
    echo "Usage: $(basename $0) command-with-parameters" >&2
}

DIE() {
    Usage
    echo "Error: $1" >&2
    exit 1
}

Main() {
    local command=()
    local xx error
    local file

    test -z "$1" && DIE "command missing"

    # command and parameters containing spaces: surround each with single quotes
    for xx in "$@" ; do
        command+=("'$xx'")
    done

    file=$(mktemp)

    # run max 3 times
    for xx in {2..0} ; do
        printf "Root " >&2

	set -o pipefail
        LANG=C /usr/bin/su -c "${command[*]}" |& tee -a $file
        error=$?
	set +o pipefail

        case $error in
            0) break ;;                # OK
            127|126) break ;;          # command is erroneous or can't be executed
            1)
		if [ -n "$(tail -n 1 $file | grep "^su: Authentication failure$")" ] ; then
		    : # wrong password, try again 2 times
		else
		    break
		fi
		;;
            *) ;;                      # signal killed command
        esac
        if [ $xx -ne 0 ] ; then
            echo "Sorry, try again ($xx)." >&2
        else
            echo "Fail." >&2
        fi
    done
    rm -f $file
}

Main "$@"
