#!/bin/bash
#
# EndeavourOS initial wallpaper installer for a user.
#


#################################################################################
EOS_SCRIPTS_YAD=/usr/share/endeavouros/scripts/eos-script-lib-yad
source $EOS_SCRIPTS_YAD || {
    echo "ERROR: cannot find $EOS_SCRIPTS_YAD" >&2
    exit 1
}
unset EOS_SCRIPTS_YAD

export -f eos_yad
export -f eos_yad_terminal
export -f eos_yad_check_internet_connection
export -f eos_yad_GetArgVal
export -f eos_yad_RunCmdTermBash
export -f eos_yad_problem
export -f eos_yad_DIE
export -f eos_yad_WARN
export -f eos_yad__detectDE
export -f eos_yad_GetDesktopName
#################################################################################


Main() {
    test -x /usr/bin/calamares && return   # don't change wallpaper while installing system

    local DE="$(eos_yad_GetDesktopName)"
    local confs=(
        "$HOME/.config/EOS-initial-wallpaper.general"
        "$HOME/.config/EOS-initial-wallpaper.$DE"
    )
    local conf

    case "$1" in
        -r)  rm -f "${confs[@]}" ;;            # -r re-installs the default wallpaper now
        -rr) rm -f "${confs[@]}" ; return ;;   # same as -r, but not now
    esac

    # Set default wallpaper only if no DE specific or general config file is found.
    for conf in "${confs[@]}" ; do
        [ -r "$conf" ] && return
    done

    eos-wallpaper-set DEFAULT    # endeavouros-wallpaper.png
    touch "${confs[0]}"  # general wallpaper!
}

Main "$@"
