#!/bin/bash
#
# Welcome: the EndeavourOS greeter.
#
# Shows useful basic info about the EndeavourOS and its usage.
# Targeted for people new to EndeavourOS (but not new to Linux).
#
# TODO:
# - add icons to buttons once proper supported exists in yad

export PROGNAME=eos-welcome
export PRETTY_PROGNAME="Welcome"

EOS_SCRIPTS_DIR=/usr/share/endeavouros/scripts
translations_dir=$EOS_SCRIPTS_DIR                 # used also by the translations-welcome.bash !!

source $translations_dir/translations-welcome.bash


#################################################################################
EOS_SCRIPTS_YAD=$EOS_SCRIPTS_DIR/eos-script-lib-yad
test -r  $EOS_SCRIPTS_YAD || {
    echo "ERROR: cannot find $EOS_SCRIPTS_YAD" >&2
    exit 1
}
source $EOS_SCRIPTS_YAD

unset EOS_SCRIPTS_YAD

#export -f eos_yad
export -f eos_yad_terminal
export -f eos_yad_check_internet_connection
export -f eos_yad_GetArgVal
export -f eos_yad_RunCmdTermBash
export -f eos_yad_problem
export -f eos_yad_DIE
export -f eos_yad_WARN
export -f eos_yad__detectDE
export -f eos_yad_GetDesktopName
#################################################################################

export PROG_PACKAGENAME="welcome"
export INSTALLER_PROGRAM=/usr/bin/calamares
export EOS_LIVEUSER=liveuser

eos_yad() {
    GDK_BACKEND=x11 /usr/bin/yad --window-icon=$EOS_WICON "$@"
}
export -f eos_yad

AfterTranslations() {
    # Here we have definitions that require special treatment because of
    # yad running in other processes...

    export WH_BUTT_TITLE="$(ltr help_butt_title)"
    export WH_BUTT_TEXT="$(ltr help_butt_text)"

    export CAL_NOAVAIL="$(ltr cal_noavail)"
    export CAL_WARN="$(ltr cal_warn)"
    export CAL_INFO1="$(ltr cal_info1)"
    export CAL_INFO2="$(ltr cal_info2)"
    export CAL_INFO3="$(ltr cal_info3)"
    export CAL_INFO4="$(ltr cal_info4)"
    export CAL_CHOOSE="$(ltr cal_choose)"
    export CAL_METHOD="$(ltr cal_method)"
    export CAL_NOSUPPORT="$(ltr cal_nosupport)"
    export CAL_NOFILE="$(ltr cal_nofile)"
    export CAL_ISTARTED="$(ltr cal_istarted)"
    export CAL_ISTOPPED="$(ltr cal_istopped)"
    export ISSUES_TITLE="$(ltr issues_title)"
    export ISSUES_FRUB="$(ltr issues_grub)"
    export ISSUES_RUN="$(ltr issues_run)"
    export ISSUES_NO="$(ltr issues_no)"
    export SYSUP_NO="$(ltr sysup_no)"
    export SYSUP_CHECK="$(ltr sysup_check)"
    export INSTALL_INSTALLER="$(ltr install_installer)"
    export INSTALL_ALREADY="$(ltr install_already)"
    export INSTALL_ING="$(ltr install_ing)"
    export INSTALL_DONE="$(ltr install_done)"
    export DM_TITLE="$(ltr dm_title)"
    export DM_COL_NAME1="$(ltr dm_col_name1)"
    export DM_COL_NAME2="$(ltr dm_col_name2)"
    export DM_REBOOT_REQUIRED="$(ltr dm_reboot_required)"
    export DM_CHANGED="$(ltr dm_changed)"
    export DM_FAILED="$(ltr dm_failed)"
    export DM_WARNING_TITLE="$(ltr dm_warning_title)"
    export AFTER_INSTALL_US="$(ltr after_install_us)"
    export AFTER_INSTALL_US_FROM="$(ltr after_install_us_from)"
    export AFTER_INSTALL_US_EL="$(ltr after_install_us_el)"
    export AFTER_INSTALL_US_DONE="$(ltr after_install_us_done)"
    export AFTER_INSTALL_US_FAIL="$(ltr after_install_us_fail)"
}

export -f ltr
export tr_strings
export SELECTED_LANGUAGE_WELCOME


IsInstalling() {
    test $show_installer -eq 1 && return 0
    test -x $INSTALLER_PROGRAM && test "$LOGNAME" = "$EOS_LIVEUSER"
}

yad_tailer() {
    local file="$1"

    tail -f "$file" | \
        eos_yad --text-info --title="$(basename "$file")" \
                --button=" $(ltr tail_butt)!dialog-close!$(ltr tail_buttip)":0 \
                --width=$width --height=$height --tail --wrap --posx=$posx --posy=$posy \
                >& /dev/null &
}
export -f yad_tailer

yad_calamares() {
    local mode="$1"                             # offline, online, choose
    local debug="$2"
    local prog=$INSTALLER_PROGRAM

    if [ ! -x $prog ] ; then
        eos_yad --text="$CAL_NOAVAIL $(basename $prog)" --title="$CAL_WARN" --height=100 --width=200 --button=yad-quit:1
        return 1
    fi

    if [ "$mode" = "choose" ] ; then
        local t1="$CAL_INFO1"
        local t2="$CAL_INFO2"
        local t3="$CAL_INFO3"
        local t4="$CAL_INFO4"
        local answer field

        if [ 0 -eq 1 ] ; then
            answer=$( eos_yad --form --title="$CAL_CHOOSE" --image=dialog-question \
                              --text="$t1$t2$t3$t4" \
                              --field="$CAL_METHOD":CB 'Offline!Online' )
            field=1
        else
            answer=$( eos_yad --list --radiolist --title="$CAL_CHOOSE" --image=dialog-question \
                              --text="$t1$t2$t3$t4" \
                              --column="Selected" --column="Method" true Offline false Online )
            field=2
        fi

        test -n "$answer" || return 1
        mode=$(echo "$answer" | cut -d '|' -f $field | tr [:upper:] [:lower:])
    fi

    case "$mode" in
        offline) ;;
        online)
            eos_yad_check_internet_connection verbose || return 1
            ;;
        *)  eos_yad_WARN "$CAL_NOSUPPORT '$mode')"     # "$PROGNAME: $FUNCNAME: unsupported mode '$mode'."
            return 1
            ;;
    esac

    local file=/usr/share/calamares/settings.conf_$mode
    if [ ! -r $file ] ; then
        eos_yad_WARN "$CAL_NOFILE '$file')"      #  "$PROGNAME: $FUNCNAME: required file '$file' does not exist!"
        return 1
    fi

    sudo cp -praf /usr/share/calamares/settings.conf_$mode         /usr/share/calamares/settings.conf
    sudo cp -praf /usr/share/calamares/modules/packages.conf_$mode /usr/share/calamares/modules/packages.conf
    sudo cp -praf /usr/share/calamares/modules/welcome.conf_$mode  /usr/share/calamares/modules/welcome.conf

    local INSTALL_LOG_FILE=/home/$EOS_LIVEUSER/endeavour-install.log

    cat <<EOF > $INSTALL_LOG_FILE
############## $INSTALL_LOG_FILE
############## $CAL_ISTARTED (UTC): $(date -u "+%Y-%m-%d %H:%M")

EOF
    local only_one_output_window=yes   # yes=one, no=more than one

    if [ "$debug" = "yes" ] ; then
        touch $INSTALL_LOG_FILE        # just making sure the file exists now
        local how_to_show_terminal=a   # one of: a b c

        case "$how_to_show_terminal" in
            a)
                local conf=/home/$EOS_LIVEUSER/.config/xfce4/terminal/terminalrc
                if [ -r $conf ] ; then
                    echo "ScrollingLines=20000"    >> $conf
                    echo "ScrollingUnlimited=TRUE" >> $conf
                fi
                eos_yad_RunCmdTermBash "tail -f $INSTALL_LOG_FILE" "" "--geometry=120x20+20+20" &
                ;;
            b)
                local posx=50
                local posy=50
                local width=600
                local height=200
                local inc=$(( height + 50 ))
                yad_tailer $INSTALL_LOG_FILE
                posy=$(( posy + inc ))
                #yad_tailer $PACMAN_LOG
                ;;
            c)
                local conf=/home/$EOS_LIVEUSER/.config/xfce4/terminal/terminalrc
                if [ -r $conf ] ; then
                    echo "ScrollingLines=20000"    >> $conf
                    echo "ScrollingUnlimited=TRUE" >> $conf
                fi
                eos_yad_RunCmdTermBash "watch -tn1 tail $INSTALL_LOG_FILE" "" "--geometry=120x40+20+20" &
                ;;
        esac
    fi

    if [ "$only_one_output_window" = "yes" ] ; then
        bash -c "pkexec $prog -d >> $INSTALL_LOG_FILE"  # calamares is running here till the end!
        printf "\n%s\n" "############## $CAL_ISTOPPED (UTC): $(date -u '+%Y-%m-%d %H:%M')" >> $INSTALL_LOG_FILE
    else
        bash -c "pkexec $prog -d >> $INSTALL_LOG_FILE" &   # calamares runs in the background
        
        local PACMAN_LOG=""
        while true
        do
            sleep 5
            PACMAN_LOG="$(/usr/bin/ls -1 /tmp/calamares-root-*/var/log/pacman.log 2>/dev/null | tail -n 1)"
            if [ -n "$PACMAN_LOG" ] ; then
                # Houston, we have a pacman log!
                break
            fi
        done
        yad_tailer $PACMAN_LOG
    fi

    # test $netlog -eq 1 && cat $INSTALL_LOG_FILE | curl -F 'f:1=<-' ix.io
}
export -f yad_calamares

yad_calamares_debug() {
    yad_calamares "$1" yes
}
export -f yad_calamares_debug

yad_UpdateMe() {
    local tmpfile=$(mktemp)
    cat <<EOF > $tmpfile
#!/bin/bash
pkexec pacman -Sy $PROG_PACKAGENAME --needed --noconfirm >& /dev/null
pkill -f "eos-welcome"
pkill -f "yad --plug"
pkill -f "yad --notebook"
eos-welcome &
rm -f $tmpfile
EOF
    bash $tmpfile
}
export -f yad_UpdateMe

yad_UpdateEOStoLatest() {    # Show what to update in order to set any EOS install at the "latest level".
    local removes=(kalu)
    local installs=(eos-update-notifier reflector-simple)
    local rem=() ins=()
    local xx
    for xx in "${removes[@]}" ; do
        pacman -Q "$xx" >& /dev/null && rem+=("$xx")
    done
    for xx in "${installs[@]}" ; do
        pacman -Q "$xx" >& /dev/null || ins+=("$xx")
    done
    
    local t1="To have your EndeavourOS install on par with the latest and greatest, the following actions are needed:\n"
    local t2="- uninstall packages: ${rem[*]}\n"
    local t3="- install packages: ${ins[*]}\n"
    local t="$t1"
    test -n "$rem" && t+="$t2"
    test -n "$ins" && t+="$t3"
    test "$t" = "$t1" && t+="Your system is already at the latest level!"
    eos_yad --text="$t" --title="Upgrading EndeavourOS level" --image=info --button=yad-ok:0
}
export -f yad_UpdateEOStoLatest

yad_PkgIssues() {
    local cpu
    local removes=()
    local commands=":"                            # These commands will be run as root.
    local title="$ISSUES_TITLE"
    local intel=0 nvidia=0 amd=0 recreate_grub_cfg=0
    local graphics
    local xx

    ## Check some "conflicting" packages.

    # Having both amd and intel microcode packages are not needed and may cause issues with grub.
    pacman -Q amd-ucode >& /dev/null && {
        pacman -Q intel-ucode >& /dev/null && {
            cpu=$(grep -w "^vendor_id" /proc/cpuinfo | head -n 1 | awk '{print $3}')
            case "$cpu" in
                GenuineIntel) removes+=(amd-ucode) ; recreate_grub_cfg=1 ;;
                *)            removes+=(intel-ucode) ; recreate_grub_cfg=1 ;;
            esac
        }
    }

    # Detecting unnecessary video drivers.
    graphics="$(device-info --vga ; device-info --display)"
    test -n "$(echo "$graphics" | grep "Intel Corporation")" && intel=1
    if [ -n "$(echo "$graphics" | grep "NVIDIA Corporation")" ] ; then
        nvidia=1
    elif [ -n "$(echo "$graphics" | grep "GeForce")" ] ; then
        nvidia=1
    fi
    if [ -n "$(echo "$graphics" | grep "Advanced Micro Devices")" ] ; then
        amd=1
    elif [ -n "$(echo "$graphics" | grep "AMD/ATI")" ] ; then
        amd=1
    elif [ -n "$(echo "$graphics" | grep "Radeon")" ] ; then
        amd=1
    fi
    if [ $intel -eq 0 ] ; then
        for xx in xf86-video-intel ; do
            pacman -Q $xx >& /dev/null && removes+=($xx)
        done
    fi
    if [ $nvidia -eq 0 ] ; then
        for xx in xf86-video-nouveau nvidia nvidia-dkms nvidia-390xx nvidia-390xx-dkms nvidia-lts nvidia-installer-dkms nvidia-settings ; do
            pacman -Q $xx >& /dev/null && removes+=($xx)
        done
    fi
    if [ $amd -eq 0 ] ; then
        for xx in xf86-video-amdgpu xf86-video-ati ; do
            pacman -Q $xx >& /dev/null && removes+=($xx)
        done
    fi

    # Remove Broadcom wifi driver if using another wifi card (some cards here only).
    xx=broadcom-wl-dkms
    pacman -Q $xx >& /dev/null && {
        local wifi_info="$(lspci -k | grep -A9 " Network controller: " | grep "Kernel driver in use")"
        if [ -n "$(echo "$wifi_info"   | grep -w iwlwifi)"] ; then
            removes+=($xx)
        elif [ -n "$(echo "$wifi_info" | grep -w ath9k)"] ; then
            removes+=($xx)
        elif [ -n "$(echo "$wifi_info" | grep -w r8169)"] ; then
            removes+=($xx)
        fi
    }

    # Make package removals as a sequence of commands.
    if [ -n "$removes" ] ; then
        commands+=" ; pacman -Rsn ${removes[*]}"
        if [ "$recreate_grub_cfg" = "1" ] ; then
            if [ -x /usr/bin/grub-mkconfig ] ; then
                commands+=" ; grub-mkconfig -o /boot/grub/grub.cfg"
            else
                eos_yad --text="$ISSUES_GRUB" --title="$title" --image=info --button=yad-ok:0
            fi
        fi
    fi

    ## Other commands to execute.

    # systemd-time-wait-sync is not needed. See https://forum.endeavouros.com/t/welcome-enos-launcher/1654/82.
    xx=systemd-time-wait-sync
    systemctl status $xx >/dev/null && {
        commands+=" ; systemctl disable $xx"
    }

    ## Now run all gathered commands.

    local cmds_as_list="$(echo "${commands[*]}" | sed -e 's|^: ; ||' -e 's| ; |\n|g')"

    if [ "$commands" != ":" ] ; then
        eos_yad_RunCmdTermBash "printf '$ISSUES_RUN\n%s\n' '$cmds_as_list' ; $EOS_ROOTER '$commands'"
    else
        local t="$ISSUES_NO"
        eos_yad --text="$t" --title="$title" --image=info --button=yad-ok:0
    fi
}
export -f yad_PkgIssues

yad_SystemUpdate_old() {
    local tmpfile=$(mktemp)
    cat <<EOF > $tmpfile
#!/bin/bash
_xx_main() {
  local updates="\$(checkupdates)"
  test -n "\$updates" && {
      echo "\$updates"
      yay -Syu # --noconfirm
  } || {
      echo "$SYSUP_NO"
  }
}
_xx_main
EOF
    chmod +x $tmpfile
    eos_yad_RunCmdTermBash "echo $SYSUP_CHECK ; $tmpfile ; rm -f $tmpfile"
}
yad_SystemUpdate() {
    local cmd
    local updates
    local hasupdates=0
    local source
    local action

    for source in upstream AUR ; do
        case "$source" in
            upstream)
                updates="$(checkupdates)"
                action="$EOS_ROOTER 'pacman -Syu'"
                ;;
            AUR)
                updates="$(yay -Qua)"
                action="yay -Syua"
                ;;
        esac
        if [ -n "$updates" ] ; then
            hasupdates=1
            cmd="echo '$AFTER_INSTALL_US_FROM $source:'"
            cmd+=" ; echo '$updates'"
            test "$source" = "upstream" && cmd+=" ; echo -n '$AFTER_INSTALL_US_EL '"
            cmd+=" ; $action && printf '\n$source $AFTER_INSTALL_US_DONE\n' || printf '\n$source $AFTER_INSTALL_US_FAIL\n'"
            eos_yad_RunCmdTermBash "$cmd"
        fi
    done
    if [ $hasupdates -eq 0 ] ; then
        eos_yad --form --text="$SYSUP_NO" --title="$AFTER_INSTALL_US" --no-focus \
                --height=100 --width=300 --timeout=10 --timeout-indicator=left \
                --button=yad-quit:0 --image=info
    fi
}
yad_SystemUpdate_fails() {
    eos-update-notifier --pkgsonly  # code re-use!
}
export -f yad_SystemUpdate

yad_InitializePacmanMirroring() {
    local tmpfile=$(mktemp)
    cat <<EOF > $tmpfile
#!/bin/bash
haveged -w 1024
pacman-key --init
pacman-key --populate
pacman-key --refresh-keys
pkill haveged
EOF
    chmod +x $tmpfile
    eos_yad_RunCmdTermBash "echo 'Initializing mirroring for pacman...' ; pkexec $tmpfile ; rm -f $tmpfile"
}
export -f yad_InitializePacmanMirroring

yad_Install() {
    # Install one or more given packages. Does not reinstall any packages.

    local yadcmd="eos_yad --text-info --title=INSTALL_INSTALLER --wrap --tail --width=600 --height=500 --button=yad-quit:0"

    local pkg pkgs=()
    for pkg in "$@" ; do
        pacman -Q "$1" >& /dev/null || pkgs+=("$pkg")
    done
    test -z "$pkgs" && {
        echo "$*: $INSTALL_ALREADY" | $yadcmd
        return
    }
    while true ; do
        echo "$INSTALL_ING ${pkgs[*]} ..."
        pkexec pacman -S --noconfirm "${pkgs[@]}"
        echo "$INSTALL_DONE"
        break
    done |& $yadcmd
}
export -f yad_Install

yad_GetCurrentDM() {
    local current=$(ls -l /etc/systemd/system/display-manager.service | awk '{print $NF}')
    current="$(basename $current .service)"
    echo "$current"
}
export -f yad_GetCurrentDM

yad_ChangeDisplayManager() {
    local cmd count
    local dmlist="" dm
    local dms=(gdm lightdm lxdm sddm)
    local current=$(yad_GetCurrentDM)

    count="${#dms[@]}"

    cmd=(eos_yad --list --radiolist --title="$DM_TITLE" --width=300 --height=200)
    cmd+=(--column="$DM_COL_NAME1":rd --column="$DM_COL_NAME2")

    for ((ix=0; ix<count; ix++)) ; do
        dm="${dms[$ix]}"
        case "$dm" in
            $current) cmd+=(true  "$dm") ;;
            *)        cmd+=(false "$dm") ;;
        esac
    done

    # selected new dm
    dm="$("${cmd[@]}" | cut -d '|' -f 2)"

    case "$dm" in
        "$current" | "") return ;;
    esac

    cmd=""
    pacman -Q "$dm" >& /dev/null || {
        case "$dm" in
            lightdm) cmd+="pacman -S ${dm}{,-gtk-greeter{,-settings}} --noconfirm >& /dev/null && ";;
            *)       cmd+="pacman -S $dm --noconfirm >& /dev/null && " ;;
        esac
    }
    cmd+="systemctl disable $current && systemctl enable $dm"
    pkexec bash -c "$cmd"

    if [ "$(yad_GetCurrentDM)" = "$dm" ] ; then
        echo "$DM_REBOOT_REQUIRED" | \
            eos_yad --text-info --title="$DM_CHANGED $dm" --wrap --width=300 --height=200 --button=yad-quit:0
    else
        echo "$DM_FAILED" | \
            eos_yad --text-info --title="$DM_WARNING_TITLE" --width=300 --height=200 --button=yad-quit:0
    fi
}
export -f yad_ChangeDisplayManager

INSTALL() {
  local handle="$1"
  local tabnum="$2"
  local _exclamation='&#33;'   # '!'
  local image=gtk-save

  eos_yad --plug="$handle" --tabnum="$tabnum" \
          --form \
          --columns=2 \
          --image=$image \
          --text="<b>$(ltr ins_text)</b>" --text-align=left \
          --field="<b>$(ltr ins_start)</b>!!$(ltr ins_starttip)":fbtn            'bash -c "yad_calamares_debug choose"' \
          --field="$(ltr ins_up)!!$(ltr ins_uptip)":fbtn                         'bash -c yad_UpdateMe' \
          --field="$(ltr ins_keys)!!$(ltr ins_keystip)":fbtn                     'bash -c yad_InitializePacmanMirroring' \
          --field="$(ltr ins_pm)!!$(ltr ins_pmtip)":fbtn                         'gparted' \
          --field="$(ltr ins_rel)!!$(ltr ins_reltip)":fbtn                       "$_BROWSER https://endeavouros.com/latest-release" \
          --field="$(ltr ins_tips)!!$(ltr ins_tipstip)":fbtn                     "$_BROWSER https://endeavouros.com/docs/installation" \
          --field="$(ltr ins_trouble)!!$(ltr ins_troubletip)":fbtn               "$_BROWSER https://endeavouros.com/docs/system-rescue" \
      &> /dev/null &

  # could use 'gparted' as the icon for gparted...
}

GeneralInfo() {
  local handle="$1"
  local tabnum="$2"
  eos_yad --plug="$handle" --tabnum="$tabnum" \
          --form \
          --columns=3 \
          --image=dialog-question \
          --text="<b>$(ltr general_info_text)</b>" --text-align=left \
          --field="$(ltr general_info_ws)!!https://endeavouros.com":fbtn          "$_BROWSER https://endeavouros.com" \
          --field="$(ltr general_info_wi)!!$(ltr general_info_witip)":fbtn        "$_BROWSER https://endeavouros.com/wiki" \
          --field="$(ltr general_info_ne)!!$(ltr general_info_netip)":fbtn        "$_BROWSER https://endeavouros.com/news" \
          --field="$(ltr general_info_fo)!!$(ltr general_info_fotip)":fbtn        "$_BROWSER https://forum.endeavouros.com" \
          --field="$(ltr general_info_do)!!$(ltr general_info_dotip)":fbtn        "$_BROWSER https://endeavouros.com/donate" \
          --field="$(ltr general_info_ab)!!$(ltr general_info_abtip)":fbtn        "$_BROWSER https://endeavouros.com/docs/applications/welcome" \
      &> /dev/null &
}

AfterInstall() {
  local handle="$1"
  local tabnum="$2"

  eos_yad --plug="$handle" --tabnum="$tabnum" \
          --form \
          --columns=2 \
          --image=dialog-information \
          --text="<b>$(ltr after_install_text)</b>" --text-align=left \
          --field=" $(ltr after_install_um)!applications-internet!$(ltr after_install_umtip)":fbtn          'reflector-simple' \
          --field=" $(ltr after_install_us)!system-software-update!$(ltr after_install_ustip)":fbtn         'bash -c yad_SystemUpdate' \
          --field=" $(ltr after_install_dsi)!face-glasses!$(ltr after_install_dsitip)":fbtn                 'bash -c yad_PkgIssues' \
          --field=" $(ltr after_install_etl)!system-software-install!$(ltr after_install_etltip)":fbtn      'bash -c yad_UpdateEOStoLatest' \
          --field=" $(ltr after_install_cdm)!preferences-desktop-display!$(ltr after_install_cdmtip)":fbtn  'bash -c yad_ChangeDisplayManager' \
          --field=" $(ltr after_install_ew)!preferences-desktop-wallpaper!$(ltr after_install_ewtip)":fbtn  'eos-set-background-picture' \
          --field="$(ltr after_install_pm)!!$(ltr after_install_pmtip)":fbtn           "$_BROWSER https://endeavouros.com/docs/pacman" \
          --field="$(ltr after_install_ay)!!$(ltr after_install_aytip)":fbtn           "$_BROWSER https://endeavouros.com/docs/aur/yay" \
          --field="$(ltr after_install_hn)!!$(ltr after_install_hntip)":fbtn           "$_BROWSER https://endeavouros.com/docs/hardware-and-network" \
          --field="$(ltr after_install_bt)!!$(ltr after_install_bttip)":fbtn           "$_BROWSER https://endeavouros.com/docs/hardware-and-network/bluetooth" \
          --field="$(ltr after_install_nv)!!$(ltr after_install_nvtip)":fbtn           "$_BROWSER https://endeavouros.com/docs/hardware-and-network/nvidia-installer" \
          --field="$(ltr after_install_ft)!!$(ltr after_install_fttip)":fbtn           "$_BROWSER https://endeavouros.com/docs/forum/how-to-include-systemlogs-in-your-post" \
      &> /dev/null &
}

AddMoreApps() {
  local handle="$1"
  local tabnum="$2"

  local gufw=""            #=gufw
  local libreoffice=""     #=libreoffice
  local chromium=""        #=chromium-browser
  local bluetooth=""       #=bluetooth

  eos_yad --plug="$handle" --tabnum="$tabnum" \
          --form \
          --columns=3 \
          --image=system-software-install \
          --text="<b>$(ltr add_more_apps_text)</b>" --text-align=left \
          --field=" LibreOffice!$libreoffice!$(ltr add_more_apps_lotip)":fbtn            'bash -c "yad_Install libreoffice-fresh"' \
          --field=" $(ltr add_more_apps_ch)!$chromium!$(ltr add_more_apps_chtip)":fbtn   'bash -c "yad_Install chromium"' \
          --field=" $(ltr add_more_apps_fw)!$gufw!$(ltr add_more_apps_fwtip)":fbtn       'bash -c "yad_Install gufw"' \
          --field=" $(ltr add_more_apps_bt)!$bluetooth!$(ltr add_more_apps_bttip)":fbtn  'bash -c "yad_Install blueberry bluez-utils"' \
      &> /dev/null &
}

About() {
  local handle="$1"
  local tabnum="$2"

  Usage | eos_yad --plug="$handle" --tabnum="$tabnum" \
                  --text-info \
                  --text="<b>More info about the $PRETTY_PROGNAME app</b>" \
                  --text-align=left \
                  --image=help-about \
      &> /dev/null &
}


# Fields explanation:
# --field="ButtonName!IconName!Tooltip":fbtn "Command"

### These variables are required:

_NOTEBOOK_TITLE="$PRETTY_PROGNAME v$(pacman -Q $PROG_PACKAGENAME | awk '{print $2}')"        # main window title

CreateNotebookCommands() {
    IsInstalling && {
        _NOTEBOOK_TABS=(                             # names of functions above
            INSTALL
            GeneralInfo
        )
    } || {
        _NOTEBOOK_TABS=(                             # names of functions above
            GeneralInfo
            AfterInstall
            AddMoreApps
            #About
        )
    }
}

####################### DO NOT CHANGE ANYTHING AFTER THIS LINE! ######################################################

DIE() {
    local title="Error"
    while true ; do
        echo "Error: $1."
        Usage
        break
    done | eos_yad_problem "$title" "$@"
    exit 1
}

WelcomeHelp() {
    Usage | eos_yad --text-info --title="$WH_BUTT_TITLE" --width=600 --height=500 \
                    --text="<b>$WH_BUTT_TEXT</b>" \
                    --text-align=left --window-icon=$EOS_WICON \
                    --image=help-about --button=yad-ok:0
}
export -f WelcomeHelp

SetBrowser() {
    local xx
    for xx in xdg-open exo-open firefox chromium ; do  # use one of these browser commands
        if [ -x /usr/bin/$xx ] ; then
            _BROWSER=/usr/bin/$xx        # for showing external links
            return
        fi
    done
    DIE "$FUNCNAME: cannot find a browser"
}

PrepareTabs() {
    local handle="$1"
    local xx ix
    ix=1
    for xx in "${_NOTEBOOK_TABS[@]}" ; do
        $xx "$handle" "$((ix++))"
    done
}

SeparateWordsWithSpaces() { # add a space before a capital letter inside a word
    local tabname="$1"

    if [ "$(echo "$tabname" | tr -d '[a-z]')" = "$tabname" ] ; then
        echo "$tabname"           # all capital letters ==> don't change
    else
        echo "$tabname" | sed -e 's|\([A-Z]\)| \1|g' -e 's|^ ||'  # add space before capital letters
    fi
}

KillExtraYad() {
    sleep 0.2
    eos-kill-yad-zombies
    return

    # There may be an extra "yad" process in vain because
    # the "save session" feature of Xfce has not stored the proper command for this app.
    #
    # The extra yad process will be eliminated by
    #   - removing the extra "yad" command from the stored session
    #   - killing the extra "yad" process if it exists

    # Remove the extra "yad" command from the saved session.
    local savefile="$(ls -1 "$HOME"/.cache/sessions/xfce4-session-* 2>/dev/null | grep -vP "\.bak$" | tail -n 1)"
    if [ -n "$savefile" ] ; then
        local count=$(grep ^LegacyCount= "$savefile" | cut -d '=' -f 2)
        local endcount=$count
        if [ "$(grep "^Legacy0_Command=yad$" "$savefile")" != "" ] || [ "$(grep "^Legacy0_Command=eos_yad$" "$savefile")" != "" ] ; then
            ((endcount--))
            sed -i "$savefile" \
                -e 's|^Legacy0_Screen=.*$||' \
                -e 's|^Legacy0_Command=.*$||' \
                -e 's|^Legacy0_ClientMachine=.*$||'
        fi
        if [ $endcount -ne $count ] ; then
            sed -i "$savefile" -e 's|^LegacyCount=.*$|LegacyCount='$endcount'|'
        fi
    fi

    # Now check if an extra "yad" process is already running. If so, simply kill it.

    sleep 0.1    # must wait a bit!

    local yadlines yadline
    local pid ppid lastword
    local processes="$(ps -ef | grep -w yad | grep -v "grep -w yad" | grep -v "^root")"  # search 'yad' without 'root'
    local problem_ppid=1

    # search for the right "extra" yad process
    if [ "$(echo "$processes" | awk '{print $NF}')" = "yad" ] ; then
        readarray -t yadlines <<< "$(echo "$processes")"
        for yadline in "${yadlines[@]}" ; do
            lastword="$(echo "$yadline" | awk '{print $NF}')"
            ppid="$(echo "$yadline" | awk '{print $3}')"
            if [ "$lastword" = "yad" ] && [ "$ppid" = "$problem_ppid" ] ; then
                # found the "extra" yad process
                pid="$(echo "$yadline" | awk '{print $2}')"
                kill $pid
                echo "$yadline" > /tmp/save-session-zombie-yad-killed.log
            fi
        done
    fi
}


WelcomeSettings() {
    local value="$1"   # enable, disable, check
    declare -A defaults
    local xx

    defaults[Greeter]="Greeter=enable"
    defaults[LastCheck]="LastCheck=0"
    defaults[OnceDaily]="OnceDaily=no"

    # Make sure we have sensible initial values in the config file.
    if [ ! -r "$WELCOME_CONFIG" ] ; then
        cat <<EOF > "$WELCOME_CONFIG"
## Configuration file for $PROGNAME.
# Note: using bash syntax.
#
# 'Greeter'   values: enable or disable.
# 'OnceDaily' values: no or yes; yes means $PROGNAME is shown only once a day.
# 'LastCheck' values: automatically filled by $PROGNAME.

EOF
    fi

    for xx in Greeter OnceDaily LastCheck ; do
        if [ -z "$(grep "^${xx}=" "$WELCOME_CONFIG" 2>/dev/null)" ] ; then
            echo "${defaults[$xx]}" >> "$WELCOME_CONFIG"
        fi
    done

    # Now the initial values are in order.

    case "$value" in
        enable | disable)
            sed -i "$WELCOME_CONFIG" -e 's|^Greeter=.*$|Greeter='"$value"'|'
            ;;
    esac

    case "$value" in
        disable)
            echo "$(ltr settings_dis_contents)" | \
                eos_yad --text-info --image=dialog-information --text="$(ltr settings_dis_text)" \
                        --title="$(ltr settings_dis_title)" \
                        --geometry=500x200 --wrap \
                        --fontname="Monospace Regular 12" \
                        --button=" $(ltr settings_dis_butt)!face-angel!$(ltr settings_dis_buttip)":0 >& /dev/null
            ;;
        check)
            grep "^Greeter=" "$WELCOME_CONFIG" 2>/dev/null | cut -d '=' -f 2
            ;;
        continue)
            # IsInstalling && { echo yes ; return ; }  # not needed, installer has default values
            if [ "$(grep "^OnceDaily=" "$WELCOME_CONFIG" 2>/dev/null | cut -d '=' -f 2)" = "no" ] ; then
                echo yes
                return
            fi
            local date="$(date +%Y%m%d)"
            if [ "$(grep "^LastCheck=" "$WELCOME_CONFIG" 2>/dev/null | cut -d '=' -f 2)" = "$date" ] ; then
                echo "Info: Stopping because of setting OnceDaily=yes in file $WELCOME_CONFIG." >&2
                echo no
            else
                echo yes
            fi
            sed -i "$WELCOME_CONFIG" -e 's|^LastCheck=.*$|LastCheck='"$date"'|'
            ;;
    esac
}

UpdateInstallScripts() {
    # IsInstalling || return
    if [ -x $INSTALLER_PROGRAM ] || [ "$LOGNAME" = "$EOS_LIVEUSER" ] ; then
        return
        # the files below are needed only for installing
    fi

    local URL=https://github.com/endeavouros-team/install-scripts/raw/master
    local scripts=(                        # may need to adjust files ...
        calamares_switcher
        chrooted_cleaner_script.sh
        cleaner_script.sh
        pacstrap_calamares
        update-mirrorlist
    )
    local script
    local tmpdir=$(mktemp -d)

    for script in "${scripts[@]}"; do
        wget -q --timeout=10 -O "$tmpdir/$script" "$URL/$script" || DIE "cannot fetch script '$script'."
        chmod +x "$tmpdir/$script"
    done
    for script in "${scripts[@]}"; do
        sudo rm -f /usr/bin/"$script"
        sudo mv "$tmpdir/$script" /usr/bin
    done
    rm -rf $tmpdir
}

Usage() {
    cat <<EOF
Usage: $PROGNAME [options]

Options:
--startdelay=X    Wait before actually starting this app.
                  X value syntax is the same as in 'sleep'.
--enable | -f     Enable this $PRETTY_PROGNAME app.
--disable         Disable this $PRETTY_PROGNAME app.
--version         Show the version of this app.
--lang=X          Use language X on the user interface.

To have $PRETTY_PROGNAME app started when you log in, make sure
- $PRETTY_PROGNAME app is selected in the Autostart feature of the DE
    OR
- "Hidden=false" is set in file /etc/xdg/autostart/welcome.desktop

On DEs that do not work well with Autostart:
You may also disable the $PRETTY_PROGNAME app from the app itself
- with the --disable option
- with a button in the app (some DEs only)

To re-enable the app, use the terminal command
    $PROGNAME --enable

Note: check also settings in the configuration file $WELCOME_CONFIG.

Option --lang=X is currently experimental and supports only a very small set
of languages. The X should consist of two lowercase letters
(like 'en' for English or 'de' for German).
If option --lang is not given, the (default) value is extracted from
the first two letters of the environment variable LANG.
EOF
}
export -f Usage


StartHere() {
    local arg lang
    local yad_zombie_log=/tmp/yad-zombies.log

    for arg in "$@" ; do
        case "$arg" in
            --lang=*) lang="${arg:7}" ;;
        esac
    done

    _init_translations "$lang" || { echo "language fail" >&2 ; exit 1 ; }

    AfterTranslations

    local WELCOME_CONFIG="$HOME/.config/EOS-greeter.conf"     # "Welcome" used to be "Greeter" ...
    KillExtraYad > $yad_zombie_log

    local show_installer=0    # explicitly show the installer, for testing only
    local start_delay=0
    local is_installing
    #local netlog=0

    for arg in "$@" ; do
        case "$arg" in
            --enable|-f) WelcomeSettings enable ;;
            --disable)   WelcomeSettings disable ; return ;;
            --startdelay=*) start_delay="${arg:13}" ;;
            --installer) show_installer=1 ;;
            --version) pacman -Q $PROG_PACKAGENAME | awk '{print $2}' ; return ;;
            --lang=*) ;; # already handled!
            #--netlog) netlog=1 ;;
            -*) DIE "unsupported option '$arg'" ;;
            *)  DIE "unsupported parameter '$arg'" ;;
        esac
    done

    if [ "$(WelcomeSettings continue)" = "no" ] ; then
        return
    fi

    CreateNotebookCommands

    if [ "$(WelcomeSettings check)" != "enable" ] ; then
        ltr2 welcome_disabled
        return
    fi

    IsInstalling
    is_installing=$?

    if [ $is_installing -eq 0 ] ; then
        :
        #if [ -z "$(grep '=/usr/share/endeavouros/scripts/welcome' /home/$EOS_LIVEUSER/.config/xfce4/panel/launcher-*/*.desktop)" ] ; then
        #    xfce4-panel --add=launcher $EOS_SCRIPTS_DIR/welcome-panel.desktop
        #fi
    else
        local verbosity
        if [ "$EOS_WELCOME_CONNECTION_WARNING" = "yes" ] ; then
            verbosity=verbose
        else
            verbosity=none
        fi
        eos_yad_check_internet_connection $verbosity 10 "" "Welcome" || return 1
    fi

    # UpdateInstallScripts

    if [ "$start_delay" != "0" ] ; then
        sleep "$start_delay"
    fi

    SetBrowser

    local handle="$(shuf -i 700000-999999 -n 1)"
    local tab tabname
    local notebook   # contains the main yad command

    PrepareTabs "$handle" || DIE "PrepareTabs failed"

    # Create the yad command gradually into an array 'notebook':

    notebook=(eos_yad --notebook --key="$handle" --center --title="$_NOTEBOOK_TITLE")
    notebook+=(--window-icon=$EOS_WICON)

    for tab in "${_NOTEBOOK_TABS[@]}" ; do
        tabname="$(ltr nb_tab_$tab)"
        #tabname="$(SeparateWordsWithSpaces "$tabname")"
        notebook+=(--tab="$tabname")
    done

    IsInstalling || notebook+=(--active-tab=2)

    notebook+=(--button=" $(ltr butt_help)!help-contents!":"bash -c WelcomeHelp")

    case "$(eos_yad_GetDesktopName)" in
        KDE | GNOME | GNOME3)
            notebook+=(--button=" $(ltr butt_later)!face-cool!$(ltr butt_latertip)":0)
            notebook+=(--button=" $(ltr butt_noshow)!face-crying!$(ltr butt_noshow)":5)
            "${notebook[@]}"
            local result=$?
            case "$result" in
                5) WelcomeSettings disable ;;
                0|252) WelcomeSettings enable ;;
            esac
            ;;
        *)
            notebook+=(--button=" $(ltr butt_later)!face-cool!":0)
            "${notebook[@]}"
            ;;
    esac
}

StartHere "$@"

exit 0
