#!/bin/bash

# Usage: ChangeDisplayResolution [resolution]

source /usr/share/endeavouros/scripts/eos-script-lib-yad || {
    echo "Error: ChangeDisplayResolution: cannot find /usr/share/endeavouros/scripts/eos-script-lib-yad" >&2
    exit 1
}
export -f eos_yad

yad_ChangeDisplayResolution() {
    local reso="$1"
    local progname="$(basename $0)"
    local query="$(xrandr --query)"
    local output="$(echo "$query" | grep " connected " | head -n 1 | awk '{print $1}')"
    local xrandr="xrandr --output $output --mode"
    local resos="$(echo "$query" | grep "^ [ ]*[0-9][0-9]*x[0-9][0-9]* " | awk '{print $1}')"
    local resosarr
    local current_reso="$(echo "$query" | grep "^ [ ]*[0-9][0-9]*x[0-9][0-9]* " | grep "*" | awk '{print $1}')"

    readarray -t resosarr <<< $(echo "$resos")

    if [ -n "$reso" ] ; then
        if [ -n "$(echo "$resos" | grep "$reso")" ] ; then
            $xrandr "$reso"
        else
            echo "Error: $progname: given resolution '$reso' is not supported." >&2
            echo "Supported values:" >&2
            for reso in "${resosarr[@]}" ; do
                if [ "$reso" = "$current_reso" ] ; then
                    echo "  * $reso"
                else
                    echo "    $reso"
                fi
            done
        fi
    else
        local cmd=(
            eos_yad
            --form --width=400 --columns=2 --image=display
            --title="Change display resolution"
            --text="Select display resolution to be used now"
            --button=yad-ok
        )
        for reso in "${resosarr[@]}" ; do
            if [ "$reso" = "$current_reso" ] ; then
                cmd+=(--field="* $reso":fbtn "$xrandr $reso")
            else
                cmd+=(--field="  $reso":fbtn "$xrandr $reso")
            fi
        done
        "${cmd[@]}" >/dev/null
    fi
}

yad_ChangeDisplayResolution "$@"
