#!/bin/bash

# Pacdiff for EndeavourOS.

SafetyWarning() {
    if [ "$EOS_PACDIFF_WARNING" = "yes" ] ; then
        local txt=""
        txt+="NOTE: <b>eos-pacdiff</b> is a powerful tool, so use it carefully!\n\n"
        txt+="For example, please do <i>not</i> modify files like:\n"
        txt+="<tt>    /etc/passwd</tt>\n"
        txt+="<tt>    /etc/group</tt>\n"
        txt+="<tt>    /etc/shadow</tt>\n"
        txt+="and related files unless you know <i>exactly</i> what you are doing.\n\n"
        txt+="You can remove this warning popup by changing the value of\n"
        txt+="variable <tt>EOS_PACDIFF_WARNING</tt> in file <tt>/etc/eos-script-lib-yad.conf</tt>.\n"
        txt+="Note that you may need to merge the changes from /etc/eos-script-lib-yad.conf.pacnew first!\n"

        eos_yad --form --image=dialog-warning --title="Warning" --text="$txt" --button=yad-quit #--width=400 --height=300
    fi
}

HasPacdiffs() { test -n "$(echo q | DIFFPROG=diff /usr/bin/pacdiff)" ; }

PacdiffCmd() {
    local differ="$1"
    local cmd="" prompt=""
    local msg=""
    
    if HasPacdiffs ; then
        case "$differ" in            # some differs may need options
            vim) differ+=" -d" ;;
        esac

        msg="Starting pacdiff & $differ as root ..."

        prompt="echo '$msg'"
        cmd="DIFFPROG='/usr/bin/$differ' su-c_wrapper -p /usr/bin/pacdiff 2>/dev/null"

        if [ $start_new_terminal = yes ] ; then
            RunInTerminal "$prompt ; $cmd"
        else
            bash -c "$prompt ; $cmd"
        fi
    else
        msg="eos-pacdiff: nothing to do."
        if [ $start_new_terminal = yes ] ; then
            eos_yad_nothing_todo "<tt>$msg</tt>" 5
        else
            echo "$msg" >&2
        fi
    fi
}

Main()
{
    local start_new_terminal=no
    [ "$1" = "--nt" ] && start_new_terminal=yes
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1
    export -f eos_yad
    export -f eos_yad_nothing_todo

    SafetyWarning

    # see /etc/eos-script-lib-yad.conf about EOS_WELCOME_PACDIFFERS

    for differ in "${EOS_WELCOME_PACDIFFERS[@]}" ; do
        if [ -x /usr/bin/$differ ] ; then
            PacdiffCmd "$differ"
            break
        fi
    done
}

Main "$@"
