#!/bin/bash

DIE() {
    echo "$progname: error: $1" >&2
    exit 1
}

Options() {
    local arg
    for arg in "$@" ; do
        case "$arg" in
            -h | --help)
                cat <<EOF
Directs standard input into $EOS_SENDLOG_URI, and saves returned URLs
into file $db.

Usage: $progname [options]
options:
    -n | --nosave   Don't save returned URL.
    -h | --help     This help.
    --man           Show manual at $EOS_SENDLOG_URI.

Configuration file $configfile (bash syntax) can be used to set variable
EOS_SENDLOG_URI.
Supported values: ${supported_uris[*]}
Default: ${supported_uris[0]}
EOF
                exit 0
                ;;
            --man)
                xdg-open "$EOS_SENDLOG_URI"
                exit 0
                ;;
            -n | --nosave)
                save=no
                ;;
            -*) DIE "unsupported option '$arg'" ;;
            *) DIE "unsupported parameter '$arg'" ;;
        esac
    done
}

SendToNet() {
    url=$(curl -F "${EOS_SENDLOG_FORM}=<-" "$EOS_SENDLOG_URI")
}

Init() {
    local ix

    [ -r $configfile ] && source $configfile

    for ((ix=0; ix < ${#supported_uris[@]}; ix++)) ; do
        if [ "$EOS_SENDLOG_URI" = "${supported_uris[$ix]}" ] ; then
            EOS_SENDLOG_FORM="${supported_forms[$ix]}"
            return
        fi
    done
    # use default:
    EOS_SENDLOG_URI="${supported_uris[0]}"
    EOS_SENDLOG_FORM="${supported_forms[0]}"
}

Main() {
    local progname="$(basename "$0")"
    local configfile=/etc/eos-sendlog.conf

    # from config file (if values are set, they must be correct!):
    local EOS_SENDLOG_URI=""
    local EOS_SENDLOG_FORM=""

    local supported_uris=(
        "http://ix.io"
        "https://clbin.com"
    )
    local supported_forms=(
        "f:1"
        "clbin"
    )

    Init
    local save=yes
    local db=$HOME/.config/$progname.txt
    local url

    Options "$@"

    SendToNet

    if [ "$save" = "yes" ] ; then
        local tmpfile=$(mktemp $HOME/.config/eos-sendlog.XXXXX)
        [ -r $db ] && mv $db $tmpfile
        printf "%s: %s\n" "$(date +%Y%m%d-%H%M)" "$url" > $db
        cat $tmpfile >> $db
        rm -f $tmpfile
    fi
    echo "$url"
}

Main "$@"
