#!/bin/bash

DIE() {
    echo "$progname: error: $1" >&2
    exit 1
}

SetBrowser() {
    local browser
    for browser in xdg-open exo-open firefox chromium vivaldi-stable opera ; do
        if [ -x /usr/bin/$browser ] ; then
            Browser=/usr/bin/$browser
            return
        fi
    done
    DIE "$FUNCNAME: cannot find a web browser"
}

EosPackages() {
    wget -q -O- https://github.com/endeavouros-team/PKGBUILDS | grep ' href="/endeavouros-team/PKGBUILDS/tree/master/' | sed 's|.*/tree/master/\([^"]*\).*|\1|' | \
        grep -P -v 'z_archived|ckbcomp'
}

HasPkgbuild() {
    local pkgs="$(EosPackages)"
    local pkg
    for pkg in $pkgs ; do
        if [ "$pkgname" = "$pkg" ] ; then
            return 0
        fi
    done
    case "$pkgname" in
        mkinitcpio-openswap)
            pkgname=openswap ; return 0 ;;
        grub-theme2-endeavouros)
            pkgname=grub-theme-endeavouros ; return 0 ;;
    esac
    return 1
}

Main()
{
    local pkgname="$1"
    local progname="$(basename "$0")"
    local urlbase=https://github.com/endeavouros-team/PKGBUILDS/commits/master
    local Browser=""

    SetBrowser

    if (HasPkgbuild) ; then
        [ -n "$Browser" ] && $Browser "$urlbase/$pkgname" >& /dev/null
    else
        eos-pkginfo "$pkgname"
    fi
}

Main "$@"
