#!/bin/bash

# On Nvidia GPU machines, kernel and nvidia driver must update together:
# - if linux-lts is updated, nvidia-lts should be updated too
# - if linux     is updated, nvidia     should be updated too
# Note that if an nvidia*dkms driver is installed, we have nothing to check.
#
# This app checks the above and informs the calling app with exit code:
#     0=success
#     1=failure
# On failure also error messages to stderr will be displayed.

Main() {
    PATH=/usr/bin:$PATH

    # Quick check is Nvidia modules are in use.

    lsmod | grep nvidia >/dev/null || exit 0

    # Some NVIDIA module is in use. Check installed packages.

    local inst=$(pacman -Qsq | grep -P '^nvidia|^linux$|^linux-lts$')

    # If any of these dkms versions are installed, we have nothing to do.

    [ -n "$(echo "$inst" | grep ^nvidia-dkms$)" ]       && exit 0
    [ -n "$(echo "$inst" | grep ^nvidia-470xx-dkms$)" ] && exit 0
    [ -n "$(echo "$inst" | grep ^nvidia-390xx-dkms$)" ] && exit 0

    # Check if "nvidia & linux" or "nvidia-lts & linux-lts" are installed.
    while true ; do
        if [ -n "$(echo "$inst" | grep ^nvidia$)" ] && [ -n "$(echo "$inst" | grep ^linux$)" ] ; then
            break
        fi
        if [ -n "$(echo "$inst" | grep ^nvidia-lts$)" ] && [ -n "$(echo "$inst" | grep ^linux-lts$)" ] ; then
            break
        fi
        exit 0   # All good, nothing more to do.
    done

    # Currently installed either:
    #    - linux     and nvidia
    #    - linux-lts and nvidia-lts
    # or both.
    # No dkms version is installed.

    # Now check that if linux* is in the updates list, corresponding nvidia* must be there too.

    local linux_lts=no
    local linux=no
    local nvidia_lts=no
    local nvidia=no
    local msgs=() msg
    local pkgs pkg

    # Find updates if they are not as parameters.
    if [ -z "$1" ] ; then
        readarray -t pkgs <<< $(checkupdates | awk '{print $1}')
    else
        pkgs=("$@")
    fi

    # Check if kernel(s) and nvidia driver(s) are in the updates list.
    for pkg in "${pkgs[@]}" ; do
        case "$pkg" in
            linux)      linux=yes ;;
            linux-lts)  linux_lts=yes ;;
            nvidia)     nvidia=yes ;;
            nvidia-lts) nvidia_lts=yes ;;
        esac
    done

    # Notify if kernel will be updated but corresponding nvidia driver not.

    [ "$linux_lts $nvidia_lts" = "yes no" ] && msgs+=("'linux-lts' would be upgraded but 'nvidia-lts' not.")
    [ "$linux $nvidia" = "yes no" ]         && msgs+=("'linux' would be upgraded but 'nvidia' not.")
    if [ -n "$msgs" ] ; then
        local progname=$(basename "$0")
        for msg in "${msgs[@]}" ; do
            echo "==> $progname: error: $msg" >&2
        done
        return 1
    fi
}

Main "$@"
