#!/bin/bash

# This program is only meant to be called by Welcome at install.

WarnExit() {
    Msg2 "$1" warning
    exit 0
}

Msg2() {
    local msg="$1"
    local type="$2"
    [ -n "$type" ] || type=info
    if [ "$LOGNAME" = "liveuser" ] && [ -x /usr/bin/calamares ] ; then
        echo "==> $progname: $type: $msg" >> $preprelogfile
    else
        echo "==> $progname: $type: $msg" >&2
    fi
}

SelectFileServer() {
    # Select file server for all code snippets

    local progname="$(basename "$0")"
    local preprelogfile=/tmp/preprelog.txt
    case "$1" in
        --logfilename) echo "$preprelogfile"; return ;;
    esac
    rm -f $preprelogfile

    # [ "$(id -u)" != "0" ] && return 0

    if ! eos-connection-checker ; then
        WarnExit "internet connection not available"
    fi

    local fserver=gitlab
    local place="$(curl -Lsm 30 https://ipinfo.io/country 2>/dev/null)"

    case "$place" in
        IR)
            # run for both liveuser and target
            fserver=github

            sudo sed -i /etc/eos-script-lib-yad.conf -e "s|^EOS_FILESERVER_SITE=.*|EOS_FILESERVER_SITE=$fserver|"
            Msg2 "set EOS_FILESERVER_SITE to $fserver"

            # run only for liveuser
            local from to file
            if [ "$LOGNAME" = "liveuser" ] && [ -x /usr/bin/calamares ] ; then

                file=/etc/calamares/modules/welcome_online.conf
                sudo sed -i $file -e "s|^\([ ]*internetCheckUrl:[ ]*\).*|\1https://$fserver.com|"
                Msg2 "changed check address to use $fserver in file $(basename $file)"

                file=/etc/calamares/modules/netinstall_community-base.conf
                from="https://gitlab.com/endeavouros-filemirror/EndeavourOS-calamares/-/raw/main/calamares/files/netinstall-ce-base.yaml"
                to="https://github.com/endeavouros-team/EndeavourOS-calamares/raw/main/calamares/files/netinstall-ce-base.yaml"
                sudo sed -i $file -e "s|$from|$to|"
                Msg2 "changed 'groupsUrl' to use $fserver in file $(basename $file)"

                file=/etc/calamares/modules/netinstall.conf
                from="https://gitlab.com/endeavouros-filemirror/EndeavourOS-calamares/-/raw/main/calamares/files/netinstall.yaml"
                to="https://github.com/endeavouros-team/EndeavourOS-calamares/raw/main/calamares/files/netinstall.yaml"
                sudo sed -i $file -e "s|$from|$to|"
                Msg2 "changed 'groupsUrl' to use $fserver in file $(basename $file)"
            fi
            ;;
    esac
    echo "$fserver"
}

SelectFileServer "$@"

