#!/bin/bash

# Copy additional wallpapers from Github's EOS site.

source /usr/share/endeavouros/scripts/eos-script-lib-yad || exit 1

DIE() {
    echo "$progname: error: $1" >&2
    exit 1
}
pushd() { command pushd "$@" >/dev/null ; }
popd()  { command popd  "$@" >/dev/null ; }

HandleWallpapers() {
    # Copy new wallpapers into their place.
    # Remove old wallpapers first.

    local url=https://github.com/EndeavourOS-Community-Editions/Community-wallpapers.git
    local urlsubdirs=(
        eos_wallpapers_classic
        eos_wallpapers_community
    )
    local targetroot=/usr/share/endeavouros/backgrounds

    local subdir
    local cmd      # real commands here
    local cmd2     # displayed commands here

    git clone "$url" || DIE "fetching wallpapers from $url failed."

    pushd "$(basename $url .git)"

    # Collect all required commands into $cmd:

    cmd="mkdir -p $targetroot"                           # collect all needed commands into $cmd

    for subdir in "${urlsubdirs[@]}" ; do
        [ -d "$subdir" ] || continue                     # skip if not folder
        if [ -d "$targetroot/$subdir" ] ; then
            echo "====> Note: will remove existing $targetroot/$subdir"
            cmd+=" ; rm -rf '$targetroot/$subdir'"       # will remove old wallpapers
        fi
        cmd+=" ; cp -r '$PWD/$subdir' $targetroot/"      # will copy new wallpapers in place
    done
    cmd2=$(echo "$cmd" | sed 's| ; |\n|g')               # reformat commands suitable for displaying

    # Now do the actual wallpaper changes:

    RunInTerminal "echo 'Running the following commands:' ; echo '$cmd2' ; $EOS_ROOTER '$cmd'"

    popd
}

Main()
{
    local progname="$(basename "$0")"
    local workdir=$(mktemp -d "$HOME/.cache/$progname.XXXXX")

    pushd "$workdir"

    HandleWallpapers

    popd

    # Cleanup
    rm -rf "$workdir"
}

Main "$@"
