#!/bin/bash

# Pacdiff for EndeavourOS.

IsInstalled() { pacman -Qq "$1" >& /dev/null ; }
HasLibs() { IsInstalled webkit2gtk ; }

SafetyWarning() {
    if [ "$EOS_PACDIFF_WARNING" = "yes" ] ; then
        local txt=""
        txt+="NOTE: <b>eos-pacdiff</b> is a powerful tool, so use it carefully!\n\n"
        txt+="For example, please do <i>not</i> modify files like:\n"
        txt+="<tt>    /etc/passwd</tt>\n"
        txt+="<tt>    /etc/group</tt>\n"
        txt+="<tt>    /etc/shadow</tt>\n"
        txt+="and related files unless you know <i>exactly</i> what you are doing.\n\n"
        txt+="You can remove this warning popup by changing the value of\n"
        txt+="variable <tt>EOS_PACDIFF_WARNING</tt> in file <tt>/etc/eos-script-lib-yad.conf</tt>.\n"
        txt+="Note that you may need to merge the changes from\nfile /etc/eos-script-lib-yad.conf.pacnew first!\n"

        if HasLibs ; then
            eos_yad --form --image=dialog-warning --title="Warning" --text="$txt" --button=yad-quit #--width=400 --height=300
        else
            txt="$(echo "$txt" | sed -e 's|<[/bit]*>||g' -e 's|\\n|\n|g')"
            printf "%s\n\n" "$txt" >&2
        fi
    fi
}

HasPacdiffs() { test -n "$(echo q | DIFFPROG=diff /usr/bin/pacdiff)" ; }
DoesSudo()    { groups | grep -Pw 'root|wheel' >/dev/null ; }

PacdiffCmd() {
    local differ="$1"
    local cmd="" prompt=""
    local msg=""
    
    if HasPacdiffs ; then
        case "$differ" in            # some differs may need options
            vim) differ+=" -d" ;;
        esac

        msg="Starting pacdiff & $differ as root ..."

        prompt="echo '$msg'"
        if DoesSudo ; then
            cmd="/usr/bin/sudo DIFFPROG='/usr/bin/$differ' /usr/bin/pacdiff 2>/dev/null"
        else
            cmd="DIFFPROG='/usr/bin/$differ' /usr/bin/su-c_wrapper -p /usr/bin/pacdiff 2>/dev/null"
        fi

        if [ $start_new_terminal = yes ] ; then
            RunInTerminal "$prompt ; $cmd"
        else
            bash -c "$prompt ; $cmd"
        fi
        return $diffs_yes
    else
        msg="eos-pacdiff: nothing to do."
        if [ $start_new_terminal = yes ] ; then
            if HasLibs ; then
                eos_yad_nothing_todo "<tt>$msg</tt>" 5
            else
                echo "$indent$msg" >&2
            fi
            return $diffs_no_nt
        else
            echo "$indent$msg" >&2
            return $diffs_no
        fi
    fi
}

Main()
{
    # exit codes
    local diffs_yes=0
    local diffs_error=1
    local diffs_no=2
    local diffs_no_nt=3

    local start_new_terminal=no
    local indent=""
    case "$1" in
        --indent=*) indent="${1#*=}" ;;
        --nt)       start_new_terminal=yes ;;
    esac
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return $diffs_error
    export -f eos_yad
    export -f eos_yad_nothing_todo

    SafetyWarning

    # see /etc/eos-script-lib-yad.conf about EOS_WELCOME_PACDIFFERS

    for differ in "${EOS_WELCOME_PACDIFFERS[@]}" ; do
        if [ -x /usr/bin/$differ ] ; then
            PacdiffCmd "$differ"
            return $?
        fi
    done
}

Main "$@"
