#!/bin/bash

# Run a command in terminal.
# See also: RunInTerminal
# Note: this is supposed to be more "fail safe" with parameters than RunInTerminal.

source /usr/share/endeavouros/scripts/eos-script-lib-yad || {
    echo "Error: cannot source eos-script-lib-yad" >&2
    exit 1
}

export -f eos_yad_terminal
export -f eos_yad_RunCmdTermBash
export -f eos_yad

Main()
{
    local xx cmd=""

    for xx in "$@" ; do
        case "" in
            -*) cmd+="$xx " ;;
            *) cmd+="'$xx' " ;;
        esac
        
    done

    eos_yad_RunCmdTermBash "$cmd"
}

Main "$@"
