#!/bin/bash

echo2()   { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }
DIE()     { echo2 "$progname: error: $1" ; Usage ; exit 1 ; }
WARN()    { echo2 "====> $progname: warning: $1" ; }

translations_dir=/usr/share/endeavouros/scripts  # needed in translations.bash

source $translations_dir/eos-script-lib-yad --limit-icons || {
    progname="$(basename "$0")"
    DIE "$translations_dir/eos-script-lib-yad not found!"
}
source $translations_dir/translations.bash || {
    progname="$(basename "$0")"
    DIE "$translations_dir/translations.bash not found!"
}

export -f eos_yad_terminal
export -f eos_yad_RunCmdTermBash

Checkupdates() {
    # Variables:
    #    in:  updates
    #    out: updates

    local retval

    updates=$(checkupdates)
    retval=$?

    echo "$updates"
    updates="$(echo "$updates" | awk '{print $1}')"

    case "$retval" in
        0)
            eos-kernel-nvidia-update-check $updates || {
                read -p "Stop upgrade (Y/n)? " >&2
                case "$REPLY" in
                    "" | [Yy]*) exit 1 ;;
                esac
            }
	    ;;
    esac
    return $retval
}

Options() {
    local pp
    for pp in "$@" ; do
        case "$pp" in
            --noup) checkArchEos=no ;;
            --noaur) checkAur=no ;;
            --lang=*) lang="${pp#*=}" ;;
            --nt) new_terminal=yes ;;
            --sync) allow_sync=yes ;;
            --keyring) keyring_first=yes ;;
            --help | -h) Usage ; return 1 ;;
            -*) DIE "unsupported option '$pp'" ;;
            *)  DIE "unsupported parameter '$pp'" ;;
        esac
        if [ "$pp" != "--nt" ] ; then
            new_terminal_options+=" $pp"
        fi
    done
}

ChecksForKeyrings() {

    # Separate keyring package updates from other updates.
    # Also make sure that package endeavouros-keyring is installed.

    local arg
    local eos_keyring=no

    for arg in $updates ; do
        case "$arg" in
            archlinux-keyring)
                krpkg+=("$arg")
                ;;
            endeavouros-keyring)
                krpkg+=("$arg")
                eos_keyring=yes
                ;;
            *)
                args+=("$arg")
                ;;
        esac
    done

    # This is for old installs that might not have package endeavouros-keyring installed:

    if [ "$eos_keyring" = "no" ] ; then
        if ! pacman -Qq endeavouros-keyring >& /dev/null ; then
            echo "==> Installing endeavouros-keyring." >&2
            krpkg+=(endeavouros-keyring)
        fi
    fi
}


Usage() {
    cat <<EOF
Usage: $progname [options]
Options:
    --noup     Don't check $upname updates.
    --noaur    Don't check AUR updates.
    --nt       Check updates in a new terminal window.
    --sync     Run program 'sync' afterwards if updates were detected.
    --keyring  Update keyring packages first. This may help on some PGP signature issues.
EOF
}

Main() {
    local checkArchEos=yes
    local checkAur=yes
    local keyring_first="$EOS_UPDATE_ARCH_KEYRING_FIRST"
    local lang=""
    local progname="$(basename "$0")"
    local upname="Arch & EndeavourOS"
    local aur_helper="$EOS_AUR_HELPER"
    local new_terminal=no
    local new_terminal_options=""  # skips only --nt
    local updates_found=no
    local allow_sync=no
    local updates
    local args=()
    local krpkg=()

    # make sure we have reasonable values
    [ -n "$keyring_first" ] || keyring_first=no
    [ -n "$aur_helper" ]    || aur_helper=yay

    Options "$@" || return

    if [ "$new_terminal" = "yes" ] ; then
        eos_yad_RunCmdTermBash "$progname $new_terminal_options"
        return
    fi

    _init_translations "$lang"         # other parameters as defaults

    if [ "$checkArchEos" = "yes" ] ; then
        echo2 "$upname $(ltr updt_update_check):"
        echo2 ":: $(ltr updt_searching) $upname $(ltr updt_for_updates)..."
        Checkupdates
        case "$?" in
            0)
                updates_found=yes
                ChecksForKeyrings
                if [ -n "${krpkg[0]}" ] && [ "$keyring_first" = "yes" ] ; then
                    $EOS_ROOTER "pacman -Sy --needed --noconfirm ${krpkg[*]} && pacman -S ${args[*]}"
                else
                    $EOS_ROOTER "pacman -Sy ${krpkg[*]} ${args[*]}"
                fi
                ;;
            1) DIE "$(echo Checkupdates: $(ltr updt_failure) | sed 's|&#33;$|!|')" ;;  # sed: exclamation mark conversion
            2) echo2 " $(ltr updt_nothing_todo)" ;;
        esac
        [ "$checkAur" = "yes" ] && echo2 ""
    fi

    if [ "$checkAur" = "yes" ] ; then
        echo2 "AUR $(ltr updt_update_check):"
        if which $aur_helper >& /dev/null ; then
            case "$aur_helper" in
                paru | */paru)
                    $aur_helper -Sua
                    if [ $? -ne 0 ] ; then
                        updates_found=yes
                    fi
                    ;;
                yay | */yay)
                    $aur_helper -Sua
                    updates_found=yes
                    ;;
            esac
        else
            echo2 ":: Warning: no AUR helper found."
            echo2 ":: Please check configuration file /etc/eos-script-lib-yad.conf,"
            echo2 ":: and check that the configured AUR helper is installed."
        fi
    fi

    if [ "$updates_found" = "yes" ] ; then
        if [ "$allow_sync" = "yes" ] || [ "$SyncAfterUpdate" = "yes" ] ; then  # SyncAfterUpdate is an environment variable
            echo2 "==> Running 'sync' after update."
            sync
        fi
    fi
}

Main "$@"
