#!/bin/bash

echo2()   { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }
DIE()     { echo2 "Error: $1" ; Usage ; exit 1 ; }

translations_dir=/usr/share/endeavouros/scripts  # needed in translations.bash

source $translations_dir/eos-script-lib-yad || {
    DIE "$translations_dir/eos-script-lib-yad not found!"
}
source $translations_dir/translations.bash || {
    DIE "$translations_dir/translations.bash not found!"
}

export -f eos_yad_terminal
export -f eos_yad_RunCmdTermBash

Options() {
    local pp
    for pp in "$@" ; do
        case "$pp" in
            --noup) checkArchEos=no ;;
            --noaur) checkAur=no ;;
            --lang=*) lang="${pp#*=}" ;;
            --nt) new_terminal=yes ;;
            --help | -h) Usage ; return 1 ;;
            -*) DIE "unsupported option '$pp'" ;;
            *)  DIE "unsupported parameter '$pp'" ;;
        esac
    done
}

Usage() {
    cat <<EOF
Usage: $progname [options]
Options:
    --noup     Don't check $upname updates.
    --noaur    Don't check AUR updates.
    --nt       Check updates in a new terminal window.
EOF
}

Main() {
    local checkArchEos=yes
    local checkAur=yes
    local lang=""
    local progname="$(basename "$0")"
    local upname="Arch & EndeavourOS"
    local aur_helper="$EOS_AUR_HELPER"
    local new_terminal=no

    [ -n "$aur_helper" ] || aur_helper=yay

    Options "$@" || return

    if [ "$new_terminal" = "yes" ] ; then
        eos_yad_RunCmdTermBash "$progname"
        return
    fi

    _init_translations "$lang"         # other parameters as defaults

    if [ "$checkArchEos" = "yes" ] ; then
        echo2 "$upname $(ltr updt_update_check):"
        echo2 ":: $(ltr updt_searching) $upname $(ltr updt_for_updates)..."
        checkupdates
        case "$?" in
            0) $EOS_ROOTER 'pacman -Syu' ;;
            1) DIE "checkupdates: $(ltr updt_failure)" ;;
            2) echo2 " $(ltr updt_nothing_todo)" ;;
        esac
        [ "$checkAur" = "yes" ] && echo2 ""
    fi

    if [ "$checkAur" = "yes" ] ; then
        echo2 "AUR $(ltr updt_update_check):"
        $aur_helper -Sua
    fi
}

Main "$@"
