#!/bin/bash

echo2()   { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }
DIE()     { echo2 "$progname: error: $1" ; Usage ; exit 1 ; }
WARN()    { echo2 "====> $progname: warning: $1" ; }

translations_dir=/usr/share/endeavouros/scripts  # needed in translations.bash

source $translations_dir/eos-script-lib-yad --limit-icons || {
    progname="$(basename "$0")"
    DIE "$translations_dir/eos-script-lib-yad not found!"
}
source $translations_dir/translations.bash || {
    progname="$(basename "$0")"
    DIE "$translations_dir/translations.bash not found!"
}

export -f eos_yad_terminal
export -f eos_yad_RunCmdTermBash

GrubCheckFwsetup() {
    if [ -d /sys/firmware/efi ] ; then              # have uefi
        if [ -x /usr/bin/grub-mkconfig ] ; then     # have grub
            local updates="$1"
            if [ -n "$(echo "$updates" | grep -w grub)" ] ; then
                local version_requiring_fwsetup="2:2.06.r322.gd9b4638c5-1"
                local curver ; curver="$(pacman -Q grub 2>/dev/null | awk '{print $NF}')"
                if [ "$(vercmp "$curver" "$version_requiring_fwsetup")" -lt "0" ] ; then
                    cat <<EOF >&2

==> IMPORTANT: you will have to run grub-install BEFORE reboot!

    Example:
        sudo grub-install --target=x86_64-efi --efi-directory=/boot/efi --bootloader-id=EndeavourOS-grub

    See https://forum.endeavouros.com/t/the-latest-grub-package-update-needs-some-manual-intervention

EOF
                fi
            fi
        fi
    fi
}

Checkupdates() {
    # Variables:
    #    in:  updates
    #    out: updates

    local retval

    if [ -n "$ufile" ] ; then
        updates=$(cat "$ufile")
        if [ -n "$(echo "$updates" | grep "Download Size")" ] ; then
            updates=$(echo "$updates" | tail -n +3)
        fi
        retval=0
    else
        updates=$(checkupdates)
        retval=$?
    fi

    echo "$updates"
    updates="$(echo "$updates" | awk '{print $1}')"

    GrubCheckFwsetup "$updates"

    case "$retval" in
        0)
            eos-kernel-nvidia-update-check $updates || {
                read -p "Stop upgrade (Y/n)? " >&2
                case "$REPLY" in
                    "" | [Yy]*) exit 1 ;;
                esac
            }
	    ;;
    esac
    return $retval
}

OptionsHandler() {
    IsBashFunction() {
        [ "$(LANG=C type "$1" 2>/dev/null | head -n1 | awk '{print $NF}')" = "function" ]
    }

    if [ -z "$progname" ] ; then
        local progname ; progname="$(/usr/bin/basename "$0")"
    fi
    local sopts="$1"
    local lopts="$2"
    local OptFunc="$3"
    local opts
    shift 3

    if [ -z "$sopts" ] || [ -z "$lopts" ] || [ -z "$OptFunc" ] ; then
        echo "$progname: parameter(s) missing" >&2
        return 1
    fi
    if ! IsBashFunction "$OptFunc"  ; then
        echo "$progname: parameter OptFunc is not a bash function" >&2
        return 1
    fi

    opts="$(/usr/bin/getopt -o="$sopts" --longoptions "$lopts" --name "$progname" -- "$@")" || {
        $OptFunc -h
        return 1
    }

    eval set -- "$opts"

    $OptFunc "$@"
}

MyOptions() {
    local pp
    while true ; do
        pp="$1"
        case "$1" in
            --noup)     checkArchEos=no ;;
            --noaur)    checkAur=no ;;
            --nt)       new_terminal=yes ;;
            --sync)     allow_sync=yes ;;
            --keyring)  keyring_first=yes ;;
            --lang)     new_terminal_options+=" $pp=$2" ; lang="$2"  ; shift ;;
            --updates)  new_terminal_options+=" $pp=$2" ; ufile="$2" ; shift ;;

            --help | -h) Usage ; return 1 ;;
            --) shift ; break ;;
            -*) DIE "unsupported option '$1'" ;;
            *)  DIE "unsupported parameter '$1'" ;;
        esac
        case "$pp" in
            --nt | --lang | --updates) ;;
            *) new_terminal_options+=" $pp" ;;
        esac
        shift
    done
}

ChecksForKeyrings() {

    # Separate keyring package updates from other updates.
    # Also make sure that package endeavouros-keyring is installed.

    local arg
    local eos_keyring=no

    for arg in $updates ; do
        case "$arg" in
            archlinux-keyring)
                krpkg+=("$arg")
                ;;
            endeavouros-keyring)
                krpkg+=("$arg")
                eos_keyring=yes
                ;;
            *)
                args+=("$arg")
                ;;
        esac
    done

    # This is for old installs that might not have package endeavouros-keyring installed:

    if [ "$eos_keyring" = "no" ] ; then
        if ! pacman -Qq endeavouros-keyring >& /dev/null ; then
            echo "==> Installing endeavouros-keyring." >&2
            krpkg+=(endeavouros-keyring)
        fi
    fi
}


Usage() {
    cat <<EOF
Usage: $progname [options]
Options:
    --noup     Don't check $upname updates.
    --noaur    Don't check AUR updates.
    --nt       Check updates in a new terminal window.
    --sync     Run program 'sync' afterwards if updates were detected.
    --keyring  Update keyring packages first. This may help on some PGP signature issues.
EOF
}

Main() {
    local checkArchEos=yes
    local checkAur=yes
    local keyring_first="$EOS_UPDATE_ARCH_KEYRING_FIRST"
    local lang=""
    local progname ; progname="$(basename "$0")"
    local upname="Arch & EndeavourOS"
    local aur_helper="$EOS_AUR_HELPER"
    local new_terminal=no
    local new_terminal_options=""  # skips only --nt
    local updates_found=no
    local allow_sync=no
    local updates
    local args=()
    local krpkg=()
    local ufile=""

    # make sure we have reasonable values
    [ -n "$keyring_first" ] || keyring_first=no
    [ -n "$aur_helper" ]    || aur_helper=yay

    OptionsHandler "h" "noup,noaur,lang:,nt,sync,keyring,updates:" MyOptions "$@" || return

    if [ "$new_terminal" = "yes" ] ; then
        eos_yad_RunCmdTermBash "$progname $new_terminal_options"
        [ -n "$ufile" ] && rm -f "$ufile"
        return
    fi

    _init_translations "$lang"         # other parameters as defaults

    if [ "$checkArchEos" = "yes" ] ; then
        echo2 "$upname $(ltr updt_update_check):"
        echo2 ":: $(ltr updt_searching) $upname $(ltr updt_for_updates)..."
        Checkupdates
        case "$?" in
            0)
                updates_found=yes
                ChecksForKeyrings
                if [ -n "${krpkg[0]}" ] && [ "$keyring_first" = "yes" ] ; then
                    $EOS_ROOTER "pacman -Sy --needed --noconfirm ${krpkg[*]} && pacman -S ${args[*]}"
                else
                    $EOS_ROOTER "pacman -Sy ${krpkg[*]} ${args[*]}"
                fi
                ;;
            1) DIE "$(echo Checkupdates: "$(ltr updt_failure)" | sed 's|&#33;$|!|')" ;;  # sed: exclamation mark conversion
            2) echo2 " $(ltr updt_nothing_todo)" ;;
        esac
        [ "$checkAur" = "yes" ] && echo2 ""
    fi

    if [ "$checkAur" = "yes" ] ; then
        echo2 "AUR $(ltr updt_update_check):"
        if which $aur_helper >& /dev/null ; then
            case "$aur_helper" in
                paru | */paru)
                    $aur_helper -Sua
                    if [ $? -ne 0 ] ; then
                        updates_found=yes
                    fi
                    ;;
                yay | */yay)
                    $aur_helper -Sua
                    updates_found=yes
                    ;;
            esac
        else
            echo2 ":: Warning: no AUR helper found."
            echo2 ":: Please check configuration file /etc/eos-script-lib-yad.conf,"
            echo2 ":: and check that the configured AUR helper is installed."
        fi
    fi

    if [ "$updates_found" = "yes" ] ; then
        ## shellcheck disable=SC2154
        if [ "$allow_sync" = "yes" ] || [ "$SyncAfterUpdate" = "yes" ] ; then  # SyncAfterUpdate is an environment variable
            echo2 "==> Running 'sync' after update."
            sync
        fi
    fi
}

Main "$@"
