#!/bin/bash

## Configuration file for program create-ml.
##
## The following timeout definitions are used only if an internet connection is used.
## All timeout values are expected to be in seconds.

## Timeout for each mirror when ranking.
## See also: create-ml option --timeout-mirror.
#
TIMEOUT_MIRROR=10

## Timeout for fetching the list of active mirrors for creating file /etc/create-ml-active-mirrors-arch.conf.
#
TIMEOUT_ACTIVE_MIRRORS=8

## Timeout values used in command 'reflector --list-countries' for creating file /etc/create-ml-country-mapping-arch.conf.
#
TIMEOUT_REFLECTOR_CONNECTION=5        # for reflector option --connection-timeout
TIMEOUT_REFLECTOR_DOWNLOAD=5          # for reflector option --download-timeout
