#!/bin/bash
#
# A workaround for grub-mkconfig's initrd line generation problem on some distros.
# This modifies two files, see their names (in "local file=...") in the functions below.
#
# NOTE: to restore old behavior, simply reinstall packages 'grub' and 'os-prober'.

_log2() {
    echo "$@" >&2
}

_log() {
    _log2 "$@"
    echo "$@" >> $log
}

_die() {
    _log "Error: $@"
    rm -f $lock
    exit 1
}

_check_file_existence() {
    local file="$1"
    local pkg="$2"
    if [ ! -r "$file" ] ; then
        case "$pkg" in
            grub)
                _die "file '$file' from package '$pkg' does not exist." \
                     "Note: if you have used grub-customizer, you may need to reinstall grub, but be careful!"
                ;;
            os-prober)
                _die "file '$file' from package '$pkg' does not exist."
                ;;
        esac
    fi
}

_backup() {
    local file="$1"
    local pkg="$2"
    _check_file_existence "$file" "$pkg"
    rm -f $file.bak       || _die "$file.bak: delete failed."
    cp -a $file $file.bak || _die "$file: backup failed."
    chmod -x $file.bak    || _die "$file.bak: chmod failed."
}

_show_result() {
    local file="$1"
    local diffs="$(diff $file $file.bak)"

    if [ "$diffs" != "" ] ; then
        _log "Changes for $file:"
        _log "$diffs"
        _log "Backup to $file.bak."
    else
        _log "$file not changed."
    fi
}

_grub_mod() {
    local file=/etc/grub.d/30_os-prober  # from package 'grub'
    _backup $file grub
    sed -i $file \
        -e "s|\(echo \${LINUX} \| cut -d ':' -f 5\)\`|\1 \| tr '^' ' '\`|"
    _show_result $file
}

_os_prober_mod() {
    local file=/usr/lib/linux-boot-probes/mounted/40grub2  # from package 'os-prober'
    _backup $file os-prober
    sed -i $file \
        -e 's|initrd="\$(echo "\$2"|shift; initrd="\$(echo "\$\@"|' \
        -e 's|initrd="/boot\$initrd"|initrd=($initrd); initrd=\${initrd[@]/#//boot}|'
    _show_result $file
}

Main() {
    local lock=/var/log/grub-fix-initrd-generation.lck
    local log=/var/log/grub-fix-initrd-generation.log

    if [ -r $lock ] ; then
        _log2 "$0 is already running!"
        return
    fi
    if [ $EUID -ne 0 ] ; then
        _log2 "Elevated privileges required!"
        return 1
    fi
    touch $lock

    rm -f $log

    _grub_mod
    _os_prober_mod

    rm -f $lock
}

Main "$@"
