#!/bin/bash

ShowUpdates() {
    local ix pkgname pkginfo dlsize prog

    # repo can be testing or stable, find out which one to use:
    /usr/bin/grep "^\[testing\]" /etc/pacman.conf >/dev/null && prog=/usr/bin/head || prog=/usr/bin/tail

    for ((ix=0; ix < ${#updates[@]}; ix++)) ; do
        pkgname="$(echo "${updates[$ix]}" | awk '{print $1}')"
        pkginfo="$(LANG=C /usr/bin/pacman -Si $pkgname)"
        dlsize="$(echo "$pkginfo" | grep "Download Size" | $prog -n 1 | awk '{print $4$5}')"
        echo "${updates[$ix]} $dlsize"
    done
}

ShowUpdatesHeader() {
    echo "Name Current -> New DownloadSize"
    echo "---- ------- -- --- ------------"
}

Main()
{
    local show_header=yes
    local updates
    local retcode=1

    test "$1" = "--nh" && show_header=no

    updates="$(/usr/bin/checkupdates)"
    retcode=$?

    case "$retcode" in
        0)
            readarray -t updates <<< $(echo "$updates")
            while true ; do
                test "$show_header" = "yes" && ShowUpdatesHeader | tr ' ' '|'
                ShowUpdates | tr ' ' '|'
                break
            done | column -t -s "|" | sed 's|\([0-9][0-9.,]*\)\([a-zA-Z][a-zA-Z]*\)$|\1 \2|'
            ;;
        1 | 2)
            return $retcode
            ;;
    esac
}

Main "$@"
