#!/bin/bash

# This program manages and configures eos-update-notifier with a small GUI.

ERROR() { echo "$progname: error: $1" >&2 ; }
DIE()   { ERROR "$1" ; exit 1 ; }

GetLibCode() {
    local libcode=/usr/share/endeavouros/scripts/eos-script-lib-yad
    source $libcode || DIE "loading $libcode failed."
    export -f eos_yad
}

GetSudoEditor() {
    local editor

    for editor in ${EOS_SUDO_EDITORS[*]} "$SUDO_EDITOR" "$VISUAL" "$EDITOR" nano ; do
        if (/usr/bin/which "$editor" >& /dev/null) ; then
            case "$editor" in
                mousepad* | /usr/bin/mousepad*)
                    Editor="dbus-launch $editor" ;;
                *)
                    Editor="$editor" ;;
            esac
            # echo "==> info: sudo-editor: $Editor" >&2
            return
        fi
    done
    DIE "suitable editor not found"
}

Main()
{
    local targetprog=eos-update-notifier
    local progname=${targetprog}-configure
    local Editor=""

    GetLibCode
    GetSudoEditor

    local cmd=(
        eos_yad
        --form --title="Configure $targetprog"
        --image=system-settings
        --text="Configure and manage features of $targetprog"
        --width=420
        --columns=2

        --field="Edit config!!<tt>View and modify configuration file /etc/$targetprog.conf with '$Editor'</tt>":fbtn \
               "/usr/bin/RunInTerminal /usr/bin/su-c_wrapper -p $Editor /etc/$targetprog.conf 2>/dev/null"
        --field="Schedule!!<tt>View and modify the schedule of update checks</tt>":fbtn \
               "/usr/bin/$targetprog --conf"
        --field="Reset!!<tt>Reset eos-update-notifier's systemd service files to defaults</tt>":fbtn \
               "/usr/bin/RunInTerminal /usr/bin/$targetprog --init-force"
        --field="Timer status!!<tt>Show status of systemd timer</tt>":fbtn \
               "/usr/bin/$targetprog --show-timer"
        --field="Operation test!!<tt>Run $targetprog now</tt>":fbtn 
               "/usr/bin/RunInTerminal /usr/bin/$targetprog --systemd -iw=0s"

        --button="Changelog!help-about!<tt>Show changelog of $targetprog</tt>":"/usr/bin/$targetprog --changelog"
        --button="yad-quit!!<tt>Quit now</tt>"
    )
    "${cmd[@]}" #> /dev/null
}

Main "$@"
