#!/bin/bash

# To be called from /etc/pacman.d/hooks/eos-reboot-required.hook.

# Implementation using libnotify.

_other_reboot_required() {
    local xx

    for xx in "$DISPLAY" "$DESKTOP_SESSION" "$XDG_CURRENT_DESKTOP" ; do
        if [ -n "$xx" ] ; then
            break
        fi
    done

    if [ -n "$xx" ] ; then
        local user userid cmd

        for user in $(/usr/bin/users) ; do
            userid=$(/usr/bin/id -u $user)
            cmd=(DISPLAY=:0 DBUS_SESSION_ADDRESS=unix:path=/run/user/$userid/bus /usr/bin/notify-send)
            cmd+=(--icon=system-reboot --urgency=critical)
            cmd+=("\"Reboot recommended!\"")
            cmd+=("\"Reboot is recommended because of recent core system package upgrades.\"")
            /usr/bin/su $user -c "${cmd[*]}"
        done
    else
        # at TTY
        echo "Reboot is recommended because of recent core system package upgrades." >&2
    fi
}
_other_reboot_required
unset -f _other_reboot_required
