#!/bin/bash

HubRelease() {
    if which logstuff >& /dev/null ; then
        if ! logstuff state ; then
            logstuff on
        fi
    fi
    hub release "$@"
}

Usage() {
    local progname=$(basename "$0")
    cat <<EOF
Usage: $progname tag [file-pattern]
EOF
    [ -n "$1" ] && exit "$1"
}

Main()
{
    local tag="$1"
    local pattern="$2"

    if [ -z "$tag" ] ; then
        Usage 0
    fi
    if [ -n "$pattern" ] ; then
        pattern="-i $pattern"
    fi

    HubRelease download $tag $pattern
}

Main "$@"
