#!/bin/bash
#
# PKGNAMES is the current build list for the packages at the [endeavouros] repository.
#
# Notes:
# - The AUR package names require suffix "/aur".
# - The EndeavourOS names are actually folder names for packages under PKGBUILDS, not actual package names!
#
# PKGNAMES_WAIT specifies which of the packages in PKGNAMES will not be built.
# Include them in quotes because we use the pipe character '|' to separate package name and the version.

PKGNAMES=(                                        # Alphabetically ordered.
    akm
    arc-gtk-theme-eos
    arc-x-icons-theme/aur

    bashdb/aur

    calamares_config_ce
    calamares_config_default
    calamares_current
    ckbcomp

    downgrade/aur
    dracut-hook/aur

    endeavouros-keyring
    endeavouros-mirrorlist
    endeavouros-skel-default
    endeavouros-skel-i3wm
    endeavouros-gschema-budgie-git
    endeavouros-gschema-gnome-git
    endeavouros-skel-lxde-git
    endeavouros-skel-lxqt-git
    endeavouros-skel-mate-git
    endeavouros-skel-plasma-git
    endeavouros-skel-xfce4
    endeavouros-theming
    endeavouros-xfce4-terminal-colors
    eos-apps-info
    eos-bash-shared
    eos-downgrade
    eos-hooks
    eos-lightdm-gtk-theme
    eos-lightdm-slick-theme
    eos-log-tool
    eos-lxdm-gtk3
    eos-packagelist
    eos-plasma-sddm-config
    eos-qogir-icons
    eos-quickstart
    eos-rankmirrors
    eos-repo-before-arch-repos
    eos-sddm-theme
    eos-skel-ce-awesome
    eos-skel-ce-bspwm
    eos-skel-ce-openbox
    eos-skel-ce-qtile
    eos-skel-ce-sway
    eos-skel-ce-worm
    eos-translations
    eos-update-notifier

    grub-theme-endeavouros

    inxi/aur

    kernel-install-for-dracut/aur
    keyserver-rank

    ly/aur

    mkinitcpio-openswap/aur

    nvidia-hook
    nvidia-inst
    nvidia-installer-common
    nvidia-installer-db
    nvidia-installer-dkms

    pahis
    paper-icon-theme
    paru/aur

    rate-mirrors/aur
    reflector-bash-completion
    reflector-simple

    welcome
    wgetpaste-eos
    worm/aur

    yad-eos
    yay/aur

    zfs-dkms/aur
    zfs-utils/aur
)

# Add packages in PKGNAMES here if they shouldn't be built right now.
# Also add the version to skip, like 'pkgname|version-to-skip', e.g. 'eos-lxdm-gtk3|0.5.3-5'.
# If all versions of a package should be in wait mode, write only the package name, e.g. 'eos-lxdm-gtk3'.

PKGNAMES_WAIT=(
    'eos-lxdm-gtk3|0.5.3-5'
)
