#!/bin/bash
#
# Check that a mirror repo has the same package and db files as the given local folder.
#

echo2() { echo "$@" >&2 ; }

DIE() {
    echo2 "Error: $1"
    exit 1
}

NameCheck() {
    local xx yy
    for xx in "$@" ; do
        for yy in $remotefilelist ; do
            test "$xx" = "$yy" && break
        done
        if [ "$xx" != "$yy" ] ; then
            echo2 "file $xx missing from $MIRROR_NAME !"
            problemfiles+="$xx "
        else
            echo2 "    OK: $xx"
        fi
    done
}

ContentsCheck() {
    local tmpdir=$(mktemp -d)
    local xx
    for xx in "$@" ; do
        wget -q --timeout=10 -O $tmpdir/$xx $MIRROR_URL/$xx || {
            echo2 "Error: fetching $xx failed."
            problemfiles+="$xx "
            continue
        }
        cmp $xx $tmpdir/$xx >/dev/null || {
            echo2 "file $xx is different !"
            problemfiles+="$xx "
            continue
        }
        echo2 "    OK: $xx"
    done
    rm -rf $tmpdir
}

Usage() {
    local progname="$(basename $0)"
    cat <<EOF >&2
$progname: Check the validity of EndeavourOS packages in the $MIRROR_NAME mirror.

Usage: $progname [parameters]
parameters:
    --full        Check contents of each file (slow) instead of just the name (fast).
    folder-name   Name of the local folder that contains package files.
                  If not given, current folder is used.
EOF
}

Main()
{
    local conf=/etc/eos-mirrorcheck.conf
    test -r $conf || DIE "configuration file $conf is required but not found."
    source $conf
    test -n "$MIRROR_URL"  || DIE "variable MIRROR_URL has no value, check file $conf."
    test -n "$MIRROR_NAME" || DIE "variable MIRROR_NAME has no value, check file $conf."

    local folder=""
    local remotefilelist
    local packages repofiles
    local problemfiles=""
    local mode=optimized
    local arg

    for arg in "$@" ; do
        case "$arg" in
            --full) mode=full ;;
            -*) Usage ; return ;;
            *) folder="$arg" ;;
        esac
    done

    test -n "$folder" || folder=.
    test -d "$folder" || DIE "folder $folder does not exist!"
    test -r "$folder/endeavouros.db" || {
        echo2 "$(basename $0): nothing to see here."
        return
    }

    echo2 "Fetching $MIRROR_NAME package info..."
    remotefilelist="$(curl -s "$MIRROR_URL" | grep '^<a href="' | sed -e 's|^<a href="||' -e 's|">.*$||')"
    test -n "$remotefilelist" || DIE "cannot fetch package info from $MIRROR_URL."

    pushd "$folder" >/dev/null

    packages="$(ls -1 *.pkg.tar.*)"
    repofiles="$(echo endeavouros.{db,files}{,.tar.xz})"

    case "$mode" in
        full)
            ContentsCheck $packages $repofiles repofiles.txt
            ;;
        optimized)
            NameCheck $packages
            ContentsCheck $repofiles repofiles.txt
            ;;
    esac

    if [ -z "$problemfiles" ] ; then
        echo2 "No issues."
    else
        echo2 -n "Problematic files: "
        echo $problemfiles
    fi
    popd >/dev/null
}

Main "$@"
