#!/bin/bash

# Check at Nvidia if the GPU database has changed.
# If it has, then offer to update the local database.

DIE()  { echo "Error: $1" >&2 ; exit 11 ; }
INFO() { printf "Info: %s" "$1" >&2 ; }
INFOln() { INFO "$1\n" ; }

nvidia-site-checks() {
    local ids=/var/lib/pci/nvidia.ids
    local newids=/tmp/nvidia.ids
    local retval=0
    local differ=/usr/bin/meld   # differ of 'code' has bugs!

    [ -x $differ ] || DIE "package 'meld' is required."

    if (! /usr/bin/ls /usr/share/licenses/nvidia* >& /dev/null) ; then
        INFO "no Nvidia driver is installed. "
    fi

    [ -r $ids ] || INFOln "$ids does not exist!"

    rm -f /tmp/nvidia*.ids
    nvidia-installer-update-db --tmpdb #2>/dev/null

    [ -r $newids ] || DIE "$newids was not generated!"

    if (diff $ids $newids >/dev/null) ; then
        : # echo "No changes." >&2
    else
        # /usr/bin/code --diff $ids $newids &     # bugs in diff output!
        $differ $ids $newids >& /dev/null &
        echo "" >&2
        read -p "Nvidia ids are changed as shown. Update local database (y/N)? " >&2
        case "$REPLY" in
            [Yy]*)
                sudo cp $newids $ids
                retval=1
                ;;
            *)
                retval=2
                ;;
        esac
    fi
    rm -f /tmp/nvidia*.ids

    return $retval
}

nvidia-site-checks "$@"

# Exit values:
#   0  no changes
#   1  changes detected and copied to local db
#   2  changes detected but not copied to local db
#   3  no nvidia driver installed
#  11  exit: a fatal error occurred
