#!/bin/bash

RELEASE_ASSETS_VERBOSE=no

echo2() {
    echo "$@" >&2
}
verbose() {
    case "$RELEASE_ASSETS_VERBOSE" in
        1|yes) echo2 "$@" ;;
    esac
}
Usage() {
    echo2 "Usage: $(basename "$0") TAG"
    echo2 "where"
    echo2 "   TAG            release tag"
}
DIE() {
    local msg="$1"
    local file_to_delete="$2"      # optional file to delete
    test -n "$file_to_delete" && rm -f "$file_to_delete"
    echo2 "ERROR: $msg"
    Usage
    exit 1
}
WARN() {
    local msg="$1"
    echo2 "Warning: $msg"
}
Info() {
    local msg="$1"
    verbose "Info: $msg"
}

Prompt() { # prompt if a prompt value is given, no newline at end
    local prompt="$1"
    test -n "$prompt" && echo2 -n "$prompt: "
}
Promptln() { # prompt if a prompt value is given, newline at end
    local prompt="$1"
    test -n "$prompt" && echo2 "$prompt:"
}

GetValueFromPipe() { # return the value from pipe's output, second token
    awk '{print $2}' | sed -e 's|^"||' -e 's|",$||' -e 's|,$||'
}
GetValueFromPipeAndIndent() { # return the value from pipe's output, second token and indented by four spaces
    awk '{print $2}' | sed -e 's|^"|    |' -e 's|",$||' -e 's|,$||'
}

GetAssetNamesFromFile() {
    local file="$1"
    local prompt_optional="$2"
    Promptln "$prompt_optional"
    grep '^      "name":' "$file" | GetValueFromPipeAndIndent
}
GetReleaseIdFromFile() {
    local file="$1"
    local prompt_optional="$2"
    Prompt "$prompt_optional"
    grep '^  "id":'       "$1" | GetValueFromPipe
}
GetTagNamesFromFile() {
    local file="$1"
    local prompt_optional="$2"
    Promptln "$prompt_optional"
    grep '^  "tag_name":' "$1" | GetValueFromPipeAndIndent
}
GetAssetIdFromFile() {
    local file="$1"
    local assetname="$2"
    local prompt_optional="$3"       # optional
    Prompt "$prompt_optional"
    grep -B2 "\"$assetname\"," "$file" | grep '"id":' | GetValueFromPipe
}


declare -A GITHUB_INFO

PrepareGithubInfo() {   # put some useful values to GITHUB_INFO
    local reponame="$1"
    local tag="$2"

    if [ -n "$reponame" ] ; then
        GITHUB_INFO["reponame"]="$reponame"
    else
        test -r .git/config || { echo2 "Need repo name but cannot find .git/config under the working folder $PWD." ; return 1 ; }
        GITHUB_INFO["reponame"]="$(basename $(grep "https://github.com" .git/config 2>/dev/null | awk '{print $3}') .git)"
        test -n "${GITHUB_INFO["reponame"]}" || { echo2 "Repo name is not available." ; return 1 ; }
    fi
    if [ -n "$tag" ] ; then
        GITHUB_INFO["tag"]="$tag"
    else
        GITHUB_INFO["tag"]="LATEST"
    fi

    test -r ~/.config/hub || { echo2 "cannot find ~/.config/hub, is 'hub' installed and initialized?" ; return 1 ; }

    #GITHUB_INFO["owner"]="$(grep "user:" ~/.config/hub | awk '{print $NF}')"
    GITHUB_INFO["owner"]="$(grep "https://github.com" .git/config | awk '{print $NF}' | sed -e 's|^https://github.com/||' -e 's|/.*$||')"
    test -n "${GITHUB_INFO["owner"]}" || { echo2 "Owner info is not available." ; return 1 ; }

    GITHUB_INFO["oauth_token"]="$(grep "oauth_token:" ~/.config/hub | awk '{print $NF}')"
    test -n "${GITHUB_INFO["oauth_token"]}" || { echo2 "Github API token is not available." ; return 1 ; }
}

GetReleaseInfoToFile()
{
    local asset_info_file="$1"
    local tag="$2"
    local reponame="$3"
    local owner
    local oauth_token

    PrepareGithubInfo "$reponame" "$tag" || DIE "PrepareGithubInfo() failed." "$asset_info_file"

    tag="${GITHUB_INFO["tag"]}"
    reponame="${GITHUB_INFO["reponame"]}"
    owner="${GITHUB_INFO["owner"]}"
    oauth_token="${GITHUB_INFO["oauth_token"]}"

    local GH_REPO="https://api.github.com/repos/$owner/$reponame"
    local GH_TAG="$GH_REPO/releases/tags/$tag"
    local AUTH="Authorization: token $oauth_token"

    test "$tag" = "LATEST" && GH_TAG="$GH_REPO/releases/latest"

    if [ "$(stat -c %s "$asset_info_file")" = "0" ] ; then
        #Info "Fetching github info..."

        # Validate token.
        curl -o /dev/null -sH "$AUTH" $GH_REPO || DIE "Invalid repo, token or network issue!" "$asset_info_file"

        # Read asset info into the file.
        curl -sH "$AUTH" $GH_TAG > $asset_info_file
    fi
}

DeleteAsset()
{
    local asset_info_file="$1"
    local asset_name="$2"

    local asset_id="$(GetAssetIdFromFile "$asset_info_file" "$asset_name")"
    local repo="${GITHUB_INFO["reponame"]}"
    local owner="${GITHUB_INFO["owner"]}"
    local oauth_token="${GITHUB_INFO["oauth_token"]}"

    if [ "$asset_id" = "" ]; then
        WARN "asset id not found for '$asset_name'."
        return 1
    fi

    Info "Deleting asset '$asset_name' (id $asset_id) ... "

    local GITHUB_OAUTH_BASIC=""  # ??

    curl $GITHUB_OAUTH_BASIC -X "DELETE" -H "Authorization: token $oauth_token" \
         "https://api.github.com/repos/$owner/$repo/releases/assets/$asset_id"
}

Main()  # parameters: TAG assetname...
{
    local xx
    local tag
    local shifts=0

    for xx in "$@" ; do
        case "$xx" in
            -v|--verbose) RELEASE_ASSETS_VERBOSE=yes ; ((shifts++)) ;;
            -*) DIE "unsupported option '$xx'" ;;
            *) tag="$xx" ; ((shifts++)) ; break ;;
        esac
    done
    shift $shifts

    # other parameters are asset names, i.e. file names without any path

    local github_asset
    local asset
    local asset_info_file

    test -n "$tag" || DIE "TAG is missing."

    # Check that the given tag exists.
    for xx in $(hub release) ; do
        test "$tag" = "$xx" && break
    done
    test "$tag" = "$xx" || DIE "TAG '$tag' does not exist." "$asset_info_file"

    asset_info_file=$(mktemp)

    GetReleaseInfoToFile "$asset_info_file" "$tag"   # repo

    # show all asset names
    test "$RELEASE_ASSETS_VERBOSE" = "yes" && verbose "Asset names:"
    for github_asset in $(GetAssetNamesFromFile "$asset_info_file") ; do
        for xx in "$@" ; do
            test "$xx" = "$github_asset" && break
        done
        test "$xx" = "$github_asset" || continue
        if [ "$RELEASE_ASSETS_VERBOSE" = "yes" ] ; then
            echo "    $github_asset"
        else
            echo "$github_asset"
        fi
    done

    rm -f "$asset_info_file"  # file no more needed
}

Main "$@"  # tag asset(s)

