#!/bin/bash

UpdateDatabase() {
    pkexec pacman -Fy >/dev/null
}

CheckDatabaseUpdate() {
    local txt=""
    local cmd

    if [ -z "$(/usr/bin/pacman -Fl eos-bash-shared 2>/dev/null)" ] ; then
        # need to run pacman -Fy
        txt+="\nPacman database needs updating using command:\n"
        txt+="<tt>  pacman -Fy</tt>\n"
        cmd=(
            eos_yad --form --title="Database update needed" --text="$txt" --image=dialog-information
            --button=yad-quit:11 --button="Update database now!system-run!":13
        )
        "${cmd[@]}"
        case "$?" in
            13) UpdateDatabase ;;
            11 | *) exit ;;
        esac
    fi
}

Main()
{
    source /usr/share/endeavouros/scripts/eos-script-lib-yad || return 1
    CheckDatabaseUpdate

    local update_label="Update database"

    local txt=""
    txt+="The buttons below will show information about the apps in the EndeavourOS repository.\n"
    txt+="<b>New</b>: a special selection of <i>bonus</i> app infos is appended!\n"
    txt+="Click an app button and an information window opens.\n"
    txt+="\n"
    if [ 0 -eq 1 ] ; then
        txt+="Note: you may have to run command\n<tt>  sudo pacman -Fy</tt>\nfirst to detect EndeavourOS commands.\n\n"
    else
        txt+="Note: you may need to click the <b>$update_label</b> button below to update your package database.\n\n"
    fi
    if [ 0 -eq 1 ] ; then
        txt+="<i>The information window(s) can contain different formats:\n"
        txt+="  - web browser\n"
        txt+="  - a pager on a terminal\n"
        txt+="  - small yad window\n"
        txt+="due to various ways the information is available.</i>\n"
    fi

    local cmd=(
        eos_yad --form --title="EndeavourOS apps info" --text="$txt" --columns=4 --align-buttons --image=dialog-information
        # --no-buttons
        --button="$update_label!!Updates package database and restarts this app":11
        --buttons-layout=center
    )
    local packages=$(/usr/bin/pacman -Sl endeavouros | /usr/bin/awk '{print $2}')
    local apps=()
    local pkg app app2

    readarray -t app <<< $(/usr/bin/pacman -Fl $packages 2>/dev/null | /usr/bin/grep "usr/bin/" | /usr/bin/grep -v "usr/bin/$" | /usr/bin/awk '{print $2}' | /usr/bin/sed 's|usr/bin/||' | /usr/bin/sort)
    [ -n "$app" ] || return 1
    apps+=("${app[@]}")

    apps+=($(eos-apps-info-helper --show-bonus))  # bonus apps!

    for app in "${apps[@]}" ; do
        case "$app" in
            # not needed here or deprecated:
            ckbcomp | eos-waiting-indicator | eos-FindAppIcon | eos-kbd-set | eos-hooks-runner | eos-reboot-required* | eos-arch-news \
                | eos-grub-fix-initrd-generation | keyserver-rank* | nvidia-installer-update-db | polybar-msg | eos-kill-yad-zombies \
                | welcome-dnd | yad-settings | yad-tools | eos-latest-arch-mirrorlist | eos-apps-info-helper | eos-install-mode-run-calamares \
                | eos-run-cmd-with-su | *.sh | *calamares* | update-mirrorlist)
                continue ;;
            eos-pkginfo | eos-pkg-changelog)
                # deprecated for now
                continue ;;

            # no support currently:
            device-info | RunInTerminalEx | RunInTerminalOpt | bashdb | yad-icon-browser | eos-pkginfo-aur)
                continue ;;

            # rename:
            eos-pkginfo-aur)  app2=eos-pkginfo ;;
            eos-welcome)      app2=welcome ;;
            su-c_wrapper)     app2="$app" ; app="su-c__wrapper" ;;   # handle underscore character !!
            *)
                app2="$app" ;;
        esac
        cmd+=(--field="$app!!$app2":fbtn "eos-apps-info-helper '$app2'")
    done

    while true ; do
        "${cmd[@]}"
        case "$?" in
            11) UpdateDatabase ;;
            *) break ;;
        esac
    done
}

Main "$@"
