#!/bin/bash

export _REFLECTOR_AUTO_FAILURE=no

_reflector_auto_die()
{
    local msg="$1"
    local code="$2"
    test -n "$msg" && { echo "Error: $msg" > /tmp/reflector-auto.log ; echo "Error: $msg" >&2 ; }
    export _REFLECTOR_AUTO_FAILURE=yes
    if [ $they_have_save -eq 0 ] ; then
        rm -f $savefile $bakfile
    fi
    exit $code
}

_get_reflector_auto_configs() {
    # Read reflector options from /etc/reflector-auto.conf
    # and convert country names to country codes.
    local REFLECTOR_AUTO_CONF="$1"
    local name code ix
    local countrynames
    local countrycodes
    local REFLECTOR_COUNTRIES="$(reflector --list-countries)"

    test -n "$REFLECTOR_COUNTRIES" || _reflector_auto_die "'reflector --list-countries' failed" 1
    REFLECTOR_COUNTRIES="$(echo "Worldwide WW 0" ; echo "$REFLECTOR_COUNTRIES")"

    readarray -t countrynames <<< "$(echo "$REFLECTOR_COUNTRIES" | sed 's|^\(.*[a-z]\)[ ]*[A-Z][A-Z].*$|\1|')"
    readarray -t countrycodes <<< "$(echo "$REFLECTOR_COUNTRIES" | awk '{print $(NF-1)}')"

    local tmpconf=$(mktemp)
    cat $REFLECTOR_AUTO_CONF | grep -P -v "^[ \t]*#|^$" > $tmpconf
    
    for ((ix=0; ix<${#countrycodes[@]}; ix++)) ; do
        name="${countrynames[$ix]}"
        if [ "${name% *}" != "$name" ] ; then                # $name contains space(s)
            code="${countrycodes[$ix]}"
            sed -i $tmpconf \
                -e "s|'$name'|$code|g" \
                -e "s|\"$name\"|$code|g"
        fi
    done
    cat $tmpconf
    rm -f $tmpconf
}

_reflector_auto_main()
{
    # Info about the options:
    #     reflector -h
    #
    # reflector-auto  configuration file: /etc/reflector-auto.conf
    #
    # Note: comment lines (first non-space char is #) or empty lines are skipped when reading the config file.

    local system_config=""
    local ml=/etc/pacman.d/mirrorlist
    local conf=/etc/reflector-auto.conf

    # If $system_config and "$@" has no --save option, then we use a temporary --save file
    # to allow a user rank mirrors without using root permissions.
    local they_have_save=0      # did user use the --save option
    local saveoption=""
    local savefile              # (temporary) new mirrorlist
    local bakfile               # for backup of old mirrorlist
    local rootcmds              # for storing possible root commands
    local xx

    if [ -r $conf ] ; then
        system_config="$(_get_reflector_auto_configs $conf)"
    fi

    test "$_REFLECTOR_AUTO_FAILURE" = "yes" && {
        echo "Problems with reading options, exit."
        return 1
    }

    for xx in $system_config "$@" ; do
        case "$xx" in
            --save) they_have_save=1 ; break ;;
        esac
    done

    if [ $they_have_save -eq 0 ] ; then
        bakfile=$(mktemp)
        cp $ml $bakfile

        savefile=$(mktemp)
        saveoption="--save $savefile"

        rootcmds="cp $bakfile $ml.bak ; cp $savefile $ml"
    fi

    /usr/bin/reflector $saveoption $system_config "$@" || _reflector_auto_die "reflector-auto failed." 1
    
    if [ $they_have_save -eq 0 ] ; then
        sudo bash -c "$rootcmds"
        rm -f $savefile $bakfile  # remove only after running the root commands
    fi
}

_reflector_auto_main "$@"
