#!/bin/bash

# Find the right Nvidia driver for a card.

echo2()   { echo   "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }

DIE() {
    echo2 "$progname: error: $1"
    exit 1
}

if false ; then
GetNvidiaIds_old()
{
    local version="$1"
    local ids="$(curl -Lsm 10 -o- https://us.download.nvidia.com/XFree86/Linux-x86_64/$version/README/supportedchips.html)"
    local true_series="${version%%.*}"

    [ -n "$ids" ] || DIE "fetcing supported ids for $version failed"

    ids="$(echo "$ids" | sed -n '1,/.*Below are the legacy GPUs that are no longer supported.*/p' | grep '<tr id=')"

    # old (340 series):
    #    <tr id="0x064C">                   # take 064C
    #
    # new (390 ... ):
    #    <tr id="devid17FD_10DE_1173">      # take 17FD
    #    <tr id="devid17FD">                # take 17FD

    if [ -n "$(echo "$ids" | grep 'id="devid')" ] ; then
        ids="$(echo "$ids" | grep '<tr id="devid' | sed 's|.*devid\([0-9A-F]*\)["_].*|\1|')"        # new
    else
        ids="$(echo "$ids" | sed 's|.*id="0x\([0-9A-F]*\)">|\1|')"                                  # old
    fi

    ids=$(echo "$ids" | sort | uniq | tr '[:upper:]' '[:lower:]')
    echo "$true_series|$ids"
}
fi

FilterIds() {
    # supports series 390 and later
    grep '<tr id="devid' | sed 's|.*devid\([0-9A-F]*\)["_].*|\1|' | sort -u | tr '[:upper:]' '[:lower:]'

    # grep 'id="devid' | grep '<tr id="devid' | sed 's|.*devid\([0-9A-F]*\)["_].*|\1|' | sort -u | tr '[:upper:]' '[:lower:]'
}

GetNvidiaIds() {
    local series="$1"
    [ -n "$series" ] || return 1
    local ids=""
    local sid1="${series_ids[0]}"   # e.g. 520
    local sid2="${series_ids[1]}"   # e.g. 470
    local sid3="${series_ids[2]}"   # e.g. 390
    local sidX="$series_id_out"

    case "$series" in
        $sid1) ids="$(echo "$ids_all" | sed -n '1,/.*Below are the legacy GPUs that are no longer supported.*/p' | FilterIds)" ;;
        $sid2) ids="$(echo "$ids_all" | sed -n "/.*\"legacy_$sid2.xx\"*/,/.*\"legacy_$sid3.xx\".*/p" | FilterIds)" ;;
        $sid3) ids="$(echo "$ids_all" | sed -n "/.*\"legacy_$sid3.xx\"*/,/.*\"legacy_$sidX.xx\".*/p" | FilterIds)" ;;
        *) DIE "unsupported series '$series'" ;;
    esac

    echo "$ids"
}

ShowDriversForId() {
    local id="$1"
    local ix
    local ids
    local ver
    local true_series=""   # found from the Nvidia website
    local ids_all
    local found=no
    local exit_code=0

    ids_all="$(curl --fail -Lsm 10 -o- "$url_of_ids")"
    exit_code=$?

    [ -n "$ids_all" ] || DIE "Nvidia id data not available from '$url_of_ids'! Curl exit code $exit_code."

    echo2 "NVIDIA card id: $id"
    echo2 "The nvidia-dkms version: $pacman_version"

    for ver in "${nvidia_versions[@]}" ; do
        true_series="${ver%%.*}"
        ids="$(GetNvidiaIds "$true_series")"
        if [ -n "$(echo "$ids" | grep "$id")" ] ; then
            printf "\nSeries %s: supported (Nvidia: %s)\n\n" "$true_series" "$ver"     # DO NOT CHANGE THIS LINE! Other apps use it.
            [ "$all" = "no" ] && return
            found=yes
        else
            [ "$all" = "yes" ] && echo2 "Series $true_series: not supported"
        fi
    done
    if [ "$found" = "no" ] ; then
        echo2 "Sorry, none of the Nvidia driver series [$(echo "${series_ids[*]}" | sed 's| |, |g')] is supported."
        printf2 "\nMore info:\n   %s\n   %s\n" "$starting_url" "$url_of_ids"
    fi
}

GetNvidiaVersions() {
    local versions=$(curl --fail -Lsm 10 -o- "$starting_url" | grep "x86_64/AMD64" | sed 's|<br>|<br>\n|g' | sed 's|.*">\([0-9\.]*\)</a>.*|\1|' | grep -Pv 'AMD64|Archive')
    local s n

    for n in $versions ; do
        for s in "${series_ids[@]}" ; do
            case "$n" in
                $s.*) nvidia_versions+=("$n") ;;
            esac
        done
    done    
}

Options() {
    local opts

    opts="$(/usr/bin/getopt -o=ha --longoptions help,all --name "$progname" -- "$@")" || {
        Options -h
        return 1
    }

    eval set -- "$opts"

    while true ; do
        case "$1" in
            -a | --all) echo2 "Info: option '$1' recognized but is no more used." ;; # all=yes ;;

            -h | --help)
                cat <<EOF >&2
Usage: $progname [options] [parameters]

Options:
  -a, --all         (Show status for all available driver branches.)
                    NOTE: this option does nothing due to implementation change.

  -h, --help        This help.

Parameters:
  card_id           Nvidia card id (4 hex numbers, lower case letters).
                    Example: 1b83
                    Note: card_id is an optional parameter.

Tip: the "card_id" value can be found with command:

  lspci -vnn | grep -P 'VGA|3D|Display' | sed 's|.*\[10de:\([0-9a-f]*\)\].*|\1|'

EOF
                exit 0
                ;;
            
            --) shift ; break ;;
        esac
        shift
    done

    nvidia_id="$1"

    case "$nvidia_id" in
        [0-9a-f][0-9a-f][0-9a-f][0-9a-f] | "") ;;
        *) DIE "given card id '$nvidia_id' is invalid" ;;
    esac
}

Main() {
    local -r progname="$(basename "$0")"
    local -r pacman_version=$(LANG=C pacman -Si nvidia-dkms | grep -w ^Version | awk '{print $NF}')
    local -r pacman_pkgver=$(echo "$pacman_version" | sed 's|-[0-9.]*$||')
    local -r pacman_version_series=${pacman_pkgver%%.*}
    local -r starting_url="https://www.nvidia.com/en-us/drivers/unix"
    local -r url_of_ids="https://us.download.nvidia.com/XFree86/Linux-x86_64/$pacman_pkgver/README/supportedchips.html"
    local all=no
    local nvidia_id=""
    local nvidia_versions=()

    Options "$@"

    local series_ids=(
        $pacman_version_series        # latest provided by Arch
        470                           # legacy series ids
        390                           # ditto
    )
    local series_id_out=367           # may change as series_ids change!

    GetNvidiaVersions                 # find versions NVIDIA is currently supporting

    if [ -z "$nvidia_id" ] ; then
        nvidia_id="$(lspci -vnn | grep -P 'VGA|Display|3D' | grep "\[10de:" | sed 's|.*\[10de:\([0-9a-f]*\).*|\1|')"
    fi
    if [ -n "$nvidia_id" ] ; then
        ShowDriversForId "$nvidia_id"
    fi
}

Main "$@"
