#!/usr/bin/env bash
#
# Rebuild the initrds for all kernels found in /usr/lib/modules
#
# Run dracut for all the installed kernels
while read -r pkgbase; do
    kernelversion=$(basename "${pkgbase%/pkgbase}")
    kernelname=$(cat "${pkgbase}")
    echo "Running dracut for ${kernelname}-${kernelversion}"
    dracut --force --hostonly --no-hostonly-cmdline "/boot/initramfs-${kernelname}.img" "${kernelversion}"
    dracut --force --no-hostonly "/boot/initramfs-${kernelname}-fallback.img" "${kernelversion}"
done < <(find /usr/lib/modules -maxdepth 2 -type f -name pkgbase)
