#!/bin/bash -e

while read -r line; do
	if [[ "${line}" == */pkgbase ]]; then
		pkgbase="$(<"/${line}")"
		kver="$(echo ${line} | cut -d/ -f4)"

		rm -rf "/boot/vmlinuz-${pkgbase}" "/boot/initramfs-${pkgbase}.img" "/boot/initramfs-${pkgbase}-fallback.img" 2> /dev/null
	fi
done
