#!/bin/bash

# Finnish translation for 'eos-update' strings.

declare -A BTR_ARR=(
    eup_msg_info            "info"
    eup_msg_warning         "warning"
    eup_msg_error           "error"
    eup_msg_helper_missing  "AUR helper not found"

    die_result_failed       "failed"

    msg_file_contains       "==> %s contains"
    msg_avail_mirrors       "    - available mirrors:   %s"
    msg_unavail_mirrors     "    - unavailable mirrors: %s"
    msg_why_sys_running     "Updating."

    tip_prog_purpose        "%s: package updater & additional features."
    tip_used_command        "==> Command: %s"
    tip_all_done            "==> All done!"

    sysup_no                "No updates."

    filelock_err            "==> File %s is in use.\n    Check if another process is still managing packages."

    warn_nvidia_chk_fail    "The compatibility check between the 'kernel' and the 'Nvidia GPU driver' failed. Using driver's dkms version may help."
    warn_param_ignored      "parameter '%s' ignored."

    # item_not_available    "%s ei nyt ole käytettävissä%s$BTR_exclamation"    # second %s not needed?
    # t1a_str               "_MULTILINE_t1a"   # älä käännä tätä riviä!
)

local _MULTILINE_t1a=(
    "Tietoja saatavilla olevista Linux-ytimistä jotka joko on asennettu tai voidaan asentaa.\n"
    "Asenna tai poista ydinpaketteja käyttäen valintaruutuja vasemmanpuoleisimmassa sarakkeessa.\n\n"
    "<i>Varmista että systeemi on täysin päivitetty ennen <b>%s:n</b> käynnistämistä</i>.\n"
    "\n"
)
