#!/bin/bash

# Finnish translation for 'eos-update' strings.

# shellcheck disable=2034,2190

declare -A BTR_ARR=(
    eup_msg_info            "tiedoksi"
    eup_msg_warning         "varoitus"
    eup_msg_error           "virhe"
    eup_msg_helper_missing  "AUR-työkalua ei löydy"

    die_result_failed       "epäonnistui"

    msg_file_contains       "==> Tiedoston %s peilipalvelimista on tällä hetkellä"
    msg_avail_mirrors       "    - toimivia:      %3s"
    msg_unavail_mirrors     "    - toimimattomia: %3s"
    msg_why_sys_running     "Päivitetään."

    tip_prog_purpose        "%s: ohjelmiston päivittäjä & lisäominaisuuksia."
    tip_used_command        "==> Komento: %s"
    tip_all_done            "==> Kaikki tehty!"

    sysup_no                "Ei päivityksiä."

    filelock_err            "==> Tiedosto %s on jo käytössä.\n    Tarkista käsitteleekö joku toinen prosessi paketteja."

    warn_nvidia_chk_fail    "Nvidian GPU-ajurin ja ytimen yhteensopivuuden tarkistus epäonnistui. GPU-ajurin dkms-version käyttö voi auttaa."
    warn_param_ignored      "parametri '%s' hylättiin ja ohitettiin."

    warn_arch_not_supported  "valitan, tämä toteutus ei tue %s-arkkitehtuuria"
)
