#!/bin/bash

## Add your preferred eos-update options to the EOS_UPDATE_OPTIONS array.
## Example:
##   EOS_UPDATE_OPTIONS+=(--keep-system-running --faillock-check
##                        --other-updates --cache-limit 2)
##
## Note: eos-update has changed option --keep-system-running to be the default.
## If you don't like the default option values pre-assigned by
## eos-update, you can simply set your own defaults by using '=' instead of '+=':
##   EOS_UPDATE_OPTIONS=(--faillock-check --other-updates --cache-limit 2)
#
EOS_UPDATE_OPTIONS+=()
