#!/bin/bash

Main() {
    local installed="$(expac -Q %n kernel-install-for-dracut eos-dracut mkinitcpio)"

    if [[ "$installed" =~ kernel-install-for-dracut ]] ; then
        reinstall-kernels
    elif [[ "$installed" =~ eos-dracut ]] ; then
        dracut-rebuild
    elif [[ "$installed" =~ mkinitcpio ]] ; then
        mkinitcpio -P
    else
        local progname="${0##*/}"
        echo "$progname: warning: cannot perform requested operation because required package(s) are missing."
    fi
}

Main "$@"
