#!/bin/bash

## REBOOT_MAX_TOTAL_WAIT defines the maximum time in seconds
## to wait before notifying about recommended reboot.
## If you install or update a package that requires more time,
## consider increasing the value accordingly to have more accurate notifications.
## Default: 300
#
REBOOT_MAX_TOTAL_WAIT=300

## REBOOT_WAIT_DIFF defined how many seconds to wait after checking again if all
## pacman-like processes have finished and the database lock filehas been released.
## This time is typically from 3 to 5 seconds.
## Default: 4
#
REBOOT_WAIT_DIFF=4

## REBOOT_NOTIFICATION_USER defines the user name to get notification about reboot recommendations.
## Then other users don't receive the notifications.
## Default: empty
## Example: REBOOT_NOTIFICATION_USER=username
#
REBOOT_NOTIFICATION_USER=""

## REBOOT_EXPIRE_TIME defines the time (in seconds) to show the reboot notification.
## Default: empty
## Example: REBOOT_EXPIRE_TIME=30
#
REBOOT_EXPIRE_TIME=""
