#!/bin/bash

echo2() { echo "$@" >&2 ; }

GetGpuIds() {
    declare -A vcodes
    vcodes[nvidia]=10de
    vcodes[intel]=8086
    vcodes[amd]=1002

    local infobase="$(lspci -vnn | grep -P 'VGA|Display')"
    local info
    local vcode
    local v id
    local result

    for v in nvidia intel amd ; do
        vcode="${vcodes[$v]}"
        info="$(echo "$infobase" | grep "\[$vcode:[0-9a-f][0-9a-f]*\]")"
        test -n "$info" || continue
        card_id="$(echo "$info" | sed -e "s|^.*\[$vcode:||" -e "s|\].*$||")"
        test -n "$result" && result+="|"
        result+="$v"
        for id in $card_id ; do
            result+=":$id"
        done
    done
    vendorinfo="$result"

    if [ $TESTING = yes ] ; then
        vendorinfo="nvidia:1dba|$result"
        vendorinfo="nvidia:06c4|$result"
    fi
}

Main()
{
    local TESTING=yes           # set to "no" on release !!!

    local vendorinfo=""             # e.g. nvidia:1234:2345|intel:4321:5432|amd:9876:6789
    local nvidia_id_file=/var/lib/pci/nvidia.ids
    local nvidia_id_file_390=/var/lib/pci/nvidia-390xx.ids
    local nvidia_info
    local id ix

    # TODO:
    #   - change nvidia-installer-dkms to use only /var/lib/pci/nvidia.ids
    #   - change nvidia-installer-update-db to update both nvidia and nvidia-390xx ids files as before

    GetGpuIds

    nvidia-installer-update-db

    nvidia_info=$(echo "$vendorinfo" | cut -d '|' -f 1)
    if [ -n "$nvidia_info" ] ; then
        ix=2
        for id in $(echo "$nvidia_info" | cut -d ':' -f $ix) ; do
            if [ -n "$(grep -w "$id" $nvidia_id_file)" ] ; then
                echo2 "Your graphics card is supported by the nvidia-dkms driver."
                echo2 "Use nvidia-installer-dkms to install the driver(s) you want."
                break
            elif [ -n "$(grep -w "$id" $nvidia_id_file_390)" ] ; then
                echo2 "Your graphics card is supported by the nvidia-390xx-dkms driver."
                echo2 "You can use nvidia-installer-dkms to install nvidia-dkms using the --force option."
                echo2 "Then, BEFORE rebooting, install nvidia-390xx-dkms from the AUR, for example:"
                echo2 "  yay -S nvidia-390xx-dkms"
                break
            fi
        done
        ((ix++))
    else
        echo2 "Nvidia card not found."
    fi
}

Main "$@"
