#!/bin/bash

echo2()   { echo "$@" >&2 ; }
printf2() { printf "$@" >&2 ; }

GetGpuIds() {
    declare -A vcodes
    vcodes[nvidia]=10de
    vcodes[intel]=8086
    vcodes[amd]=1002

    local infobase="$(lspci -vnn | grep -P 'VGA|Display|3D')"
    local info
    local vcode
    local v id
    local result=""

    for v in nvidia intel amd ; do
        vcode="${vcodes[$v]}"
        info="$(echo "$infobase" | grep "\[$vcode:[0-9a-f][0-9a-f]*\]")"
        test -n "$info" || continue
        card_id="$(echo "$info" | sed -e "s|^.*\[$vcode:||" -e "s|\].*$||")"
        test -n "$result" && result+="|"
        result+="$v"
        for id in $card_id ; do
            result+=":$id"
        done
    done
    vendorinfo="$result"

    case "$1" in
        "")
            ;;
        internal-test)
            vendorinfo="nvidia:1dba|$result"
            vendorinfo="nvidia:06c4|$result"
            #vendorinfo="nvidia:aaaa|$result"
            #vendorinfo="nvidia:aaaa:bbbb|$result"
            vendorinfo="nvidia:06c4:1dba|$result"
            ;;
        [0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F])            # id = 4 hex numbers
            id="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
            vendorinfo="nvidia:$id"
            ;;
        *:[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F])          # id = 4 hex numbers
            id="$(echo "$1" | tr '[:upper:]' '[:lower:]')"
            vendorinfo="$id"
            ;;
        *)
            printf2 "Warning: unsupported parameter '$1' is ignored.\n\n"
            Usage2
            exit 1
            ;;
    esac
}

Usage2() {
    cat <<EOF >&2
Usage: $progname [<nvidia-id> | internal-test]
where
    <nvidia-id>     Check if an Nvidia card with given id (4 hex numbers) is supported.
    internal-test   Internal ad hoc test (useful for devs only).

If no parameter is given, check if the currently installed Nvidia card is supported.

Program return codes:
    0 = nvidia-dkms is supported
    2 = only nvidia-390x-dkms is supported (obsolete)
    1 = no Nvidia card detected or not supported
EOF
}

Main()
{
    local progname=nvidia-installer-check
    local vendorinfo=""        # e.g. nvidia:1234:2345|intel:4321:5432|amd:9876:6789
    local db_dir=/tmp          # /var/lib/pci
    local nvidia_id_file=$db_dir/nvidia.ids
    local nvidia_id_file_390=$db_dir/nvidia-390xx.ids
    local nvidia_info
    local id ids=""
    local ret_ids
    local driver_found=""
    local resultcode=1
    local TESTING=no           # set to "no" on release !!!

    GetGpuIds "$@"
    nvidia_info=$(echo "$vendorinfo" | cut -d '|' -f 1 | grep nvidia)

    if [ -n "$nvidia_info" ] ; then
        nvidia-installer-update-db --tmpdb  >& /dev/null      # --tmpdb: files go to /tmp
        ret_ids="$(echo "$nvidia_info" | sed -e 's|^nvidia:||' -e 's|:| |')"
        for id in $ret_ids ; do
            if [ -n "$(grep -w "$id" $nvidia_id_file)" ] ; then
                cat <<EOF >&2
Your graphics card (id: $id) is supported by the nvidia-dkms driver.
To install a driver for this card, you can use nvidia-installer-dkms.

EOF
                driver_found+=" nvidia-dkms"
            elif [ -n "$(grep -w "$id" $nvidia_id_file_390)" ] ; then
                cat <<EOF >&2
Your graphics card (id: $id) is supported by the nvidia-390xx-dkms driver.
To install a driver for this card:
  * Use the --force option with nvidia-installer-dkms.
  * Then, BEFORE rebooting, install nvidia-390xx-dkms from the AUR.
    For example:
      yay -S nvidia-390xx-dkms

EOF
                driver_found+=" nvidia-390xx-dkms"
            else
                if [ -z "$ids" ] ; then
                    ids=($id)
                else
                    ids+=($id)
                fi
            fi
        done
        case "$driver_found" in
            *nvidia-dkms*)        resultcode=0 ;;
            " nvidia-390xx-dkms") resultcode=2 ;;
            *)
                if [ ${#ids[@]} -eq 1 ] ; then
                    echo2 "Sorry, your Nvidia card (id: ${ids[*]}) is not supported by nvidia-dkms nor nvidia-390xx-dkms."
                else
                    echo2 "Sorry, your Nvidia cards (ids: ${ids[*]}) are not supported by nvidia-dkms nor nvidia-390xx-dkms."
                fi
                ;;
        esac
        rm -f $nvidia_id_file $nvidia_id_file_390
    else
        case "$vendorinfo" in
            nvidia:*) echo2 "Card '$vendorinfo' not found." ;;
            *)        echo2 "Sorry, card '$vendorinfo' not checked by this program." ;;
        esac
    fi

    return $resultcode         # 0=OK, 1=FAIL, 2=OK (but only 390xx)
}

Main "$@"
